
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package it.unibas.freesbee.websla.ws.web.stub;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-11-26T12:15:04.411+01:00
 * Generated source version: 2.7.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "WSAutenticazioneImplService",
                      portName = "WSAutenticazioneImplPort",
                      targetNamespace = "http://web.ws.freesbeesla.unibas.it/",
                      wsdlLocation = "http://localhost:28080/freesbee-Sla/ws/autenticazione?wsdl",
                      endpointInterface = "it.unibas.freesbee.websla.ws.web.stub.IWSAutenticazione")
                      
public class IWSAutenticazioneImpl implements IWSAutenticazione {

    private static final Logger LOG = Logger.getLogger(IWSAutenticazioneImpl.class.getName());

    /* (non-Javadoc)
     * @see it.unibas.freesbee.websla.ws.web.stub.IWSAutenticazione#cambiaPassword(java.lang.String  nuovaPassword ,)java.lang.String  nomeUtente )*
     */
    public void cambiaPassword(java.lang.String nuovaPassword,java.lang.String nomeUtente) throws SOAPFault_Exception    { 
        LOG.info("Executing operation cambiaPassword");
        System.out.println(nuovaPassword);
        System.out.println(nomeUtente);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SOAPFault_Exception("SOAPFault...");
    }

    /* (non-Javadoc)
     * @see it.unibas.freesbee.websla.ws.web.stub.IWSAutenticazione#autentica(java.lang.String  nomeUtente )*
     */
    public void autentica(java.lang.String nomeUtente) throws SOAPFault_Exception    { 
        LOG.info("Executing operation autentica");
        System.out.println(nomeUtente);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SOAPFault_Exception("SOAPFault...");
    }

}
