
package it.unibas.freesbee.websla.ws.web.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Tue Apr 14 15:28:55 CEST 2009
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebService(targetNamespace = "http://web.ws.freesbeesla.unibas.it/", name = "ServiceConfigura")

public interface ServiceConfigura {

    @RequestWrapper(localName = "modificaConfigurazioneSP", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.ModificaConfigurazioneSP")
    @ResponseWrapper(localName = "modificaConfigurazioneSPResponse", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.ModificaConfigurazioneSPResponse")
    @WebMethod
    public void modificaConfigurazioneSP(
        @WebParam(name = "datiConfigurazione", targetNamespace = "")
        DatiConfigurazione datiConfigurazione
    ) throws SOAPFault_Exception;

    @WebResult(name = "datiConfigurazione", targetNamespace = "")
    @RequestWrapper(localName = "caricaConfigurazione", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.CaricaConfigurazione")
    @ResponseWrapper(localName = "caricaConfigurazioneResponse", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.CaricaConfigurazioneResponse")
    @WebMethod
    public DatiConfigurazione caricaConfigurazione() throws SOAPFault_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "verificaNica", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.VerificaNica")
    @ResponseWrapper(localName = "verificaNicaResponse", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.VerificaNicaResponse")
    @WebMethod
    public java.lang.String verificaNica() throws SOAPFault_Exception;

    @RequestWrapper(localName = "modificaConfigurazioneSLA", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.ModificaConfigurazioneSLA")
    @ResponseWrapper(localName = "modificaConfigurazioneSLAResponse", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.ModificaConfigurazioneSLAResponse")
    @WebMethod
    public void modificaConfigurazioneSLA(
        @WebParam(name = "datiConfigurazione", targetNamespace = "")
        DatiConfigurazione datiConfigurazione
    ) throws SOAPFault_Exception;
}
