package it.unibas.freesbee.websla.ws.web.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-12-12T22:13:17.691+01:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://web.ws.freesbeesla.unibas.it/", name = "ServiceSoggetto")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceSoggetto {

    @WebResult(name = "soggetto", targetNamespace = "")
    @RequestWrapper(localName = "getSoggettiInf2", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.GetSoggettiInf2")
    @WebMethod
    @ResponseWrapper(localName = "getSoggettiInf2Response", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.GetSoggettiInf2Response")
    public java.util.List<Soggetto> getSoggettiInf2() throws SOAPFault_Exception;

    @WebResult(name = "soggetto", targetNamespace = "")
    @RequestWrapper(localName = "getSoggettiNica", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.GetSoggettiNica")
    @WebMethod
    @ResponseWrapper(localName = "getSoggettiNicaResponse", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.GetSoggettiNicaResponse")
    public java.util.List<Soggetto> getSoggettiNica() throws SOAPFault_Exception;

    @WebResult(name = "soggetto", targetNamespace = "")
    @RequestWrapper(localName = "getSoggettiSLA", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.GetSoggettiSLA")
    @WebMethod
    @ResponseWrapper(localName = "getSoggettiSLAResponse", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.GetSoggettiSLAResponse")
    public java.util.List<Soggetto> getSoggettiSLA(
        @WebParam(name = "nomeAccordoServizio", targetNamespace = "")
        java.lang.String nomeAccordoServizio,
        @WebParam(name = "nomeServizio", targetNamespace = "")
        java.lang.String nomeServizio,
        @WebParam(name = "tipoServizio", targetNamespace = "")
        java.lang.String tipoServizio
    ) throws SOAPFault_Exception;

    @RequestWrapper(localName = "removeSoggettoInf2", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.RemoveSoggettoInf2")
    @WebMethod
    @ResponseWrapper(localName = "removeSoggettoInf2Response", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.RemoveSoggettoInf2Response")
    public void removeSoggettoInf2(
        @WebParam(name = "soggetto", targetNamespace = "")
        Soggetto soggetto
    ) throws SOAPFault_Exception;

    @RequestWrapper(localName = "addSoggettoInf2", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.AddSoggettoInf2")
    @WebMethod
    @ResponseWrapper(localName = "addSoggettoInf2Response", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.AddSoggettoInf2Response")
    public void addSoggettoInf2(
        @WebParam(name = "soggetto", targetNamespace = "")
        Soggetto soggetto
    ) throws SOAPFault_Exception;
}
