
package it.unibas.freesbee.websla.ws.web.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;

/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Wed Sep 03 15:35:51 CEST 2008
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebService(targetNamespace = "http://web.ws.freesbeesla.unibas.it/", name = "ServiceMonitoraggioStatistiche")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)

public interface ServiceMonitoraggioStatistiche {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "statisticheErogatoreResponse", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", partName = "parameters")
    @WebMethod
    public StatisticheErogatoreResponse statisticheErogatore(
        @WebParam(partName = "parameters", name = "statisticheErogatore", targetNamespace = "http://web.ws.freesbeesla.unibas.it/")
        StatisticheErogatore parameters
    ) throws SOAPFault_Exception;
}
