
package it.unibas.freesbee.websla.ws.web.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Tue Apr 14 15:28:55 CEST 2009
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebServiceClient(name = "ServiceConfigura", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", wsdlLocation = "file:ServiceConfigura.wsdl")
public class ServiceConfigura_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://web.ws.freesbeesla.unibas.it/", "ServiceConfigura");
    public final static QName ServiceConfigura = new QName("http://web.ws.freesbeesla.unibas.it/", "ServiceConfigura");
    static {
        URL url = null;
        try {
            url = new URL("file:ServiceConfigura.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:ServiceConfigura.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public ServiceConfigura_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceConfigura_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceConfigura_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns ServiceConfigura
     */
    @WebEndpoint(name = "ServiceConfigura")
    public ServiceConfigura getServiceConfigura() {
        return (ServiceConfigura)super.getPort(ServiceConfigura, ServiceConfigura.class);
    }

}
