
package it.unibas.freesbee.websla.ws.web.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-12-12T23:04:16.138+01:00
 * Generated source version: 2.7.7
 * 
 */
@WebService(targetNamespace = "http://web.ws.freesbeesla.unibas.it/", name = "ServiceServizio")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceServizio {

    @WebResult(name = "servizio", targetNamespace = "")
    @RequestWrapper(localName = "getServiziInf2Fruiti", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.GetServiziInf2Fruiti")
    @WebMethod
    @ResponseWrapper(localName = "getServiziInf2FruitiResponse", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.GetServiziInf2FruitiResponse")
    public java.util.List<Servizio> getServiziInf2Fruiti() throws SOAPFault_Exception;

    @RequestWrapper(localName = "updateServizioActive", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.UpdateServizioActive")
    @WebMethod
    @ResponseWrapper(localName = "updateServizioActiveResponse", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.UpdateServizioActiveResponse")
    public void updateServizioActive(
        @WebParam(name = "servizio", targetNamespace = "")
        Servizio servizio
    ) throws SOAPFault_Exception;

    @WebResult(name = "servizio", targetNamespace = "")
    @RequestWrapper(localName = "getServiziInf2Erogati", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.GetServiziInf2Erogati")
    @WebMethod
    @ResponseWrapper(localName = "getServiziInf2ErogatiResponse", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.GetServiziInf2ErogatiResponse")
    public java.util.List<Servizio> getServiziInf2Erogati() throws SOAPFault_Exception;

    @WebResult(name = "servizio", targetNamespace = "")
    @RequestWrapper(localName = "getServiziNicaNonMonitorati", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.GetServiziNicaNonMonitorati")
    @WebMethod
    @ResponseWrapper(localName = "getServiziNicaNonMonitoratiResponse", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.GetServiziNicaNonMonitoratiResponse")
    public java.util.List<Servizio> getServiziNicaNonMonitorati() throws SOAPFault_Exception;

    @RequestWrapper(localName = "addServizio", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.AddServizio")
    @WebMethod
    @ResponseWrapper(localName = "addServizioResponse", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.AddServizioResponse")
    public void addServizio(
        @WebParam(name = "servizio", targetNamespace = "")
        Servizio servizio,
        @WebParam(name = "arg1", targetNamespace = "")
        byte[] arg1
    ) throws SOAPFault_Exception;

    @WebResult(name = "parametroSla", targetNamespace = "")
    @RequestWrapper(localName = "getParametriSla", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.GetParametriSla")
    @WebMethod
    @ResponseWrapper(localName = "getParametriSlaResponse", targetNamespace = "http://web.ws.freesbeesla.unibas.it/", className = "it.unibas.freesbeesla.ws.web.GetParametriSlaResponse")
    public java.util.List<java.lang.String> getParametriSla(
        @WebParam(name = "servizio", targetNamespace = "")
        Servizio servizio
    ) throws SOAPFault_Exception;
}
