<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2008

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://ws.ap6.progettoicar.it/" exclude-result-prefixes="xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/datiCompleti">
		<getRilevazioni>
			<xsl:attribute name="xsi:schemaLocation">
				<xsl:value-of select="'http://ws.ap6.progettoicar.it/ C:/DOCUME~1/LAGUAR~1/Desktop/target.xsd'"/>
			</xsl:attribute>
			<rilevazioniXML xmlns="">
				<xsl:for-each select="datiCostanti">
					<xsl:for-each select="data_rilevazione">
						<xsl:attribute name="data_rilevazione">
							<xsl:value-of select="."/>
						</xsl:attribute>
					</xsl:for-each>
				</xsl:for-each>
				<xsl:for-each select="datiCostanti">
					<xsl:for-each select="codistatregione">
						<xsl:attribute name="codistatregione">
							<xsl:value-of select="."/>
						</xsl:attribute>
					</xsl:for-each>
				</xsl:for-each>
				<rilevazionitype>
				<xsl:for-each select="datiDB">
					<rilevazioneitem>
								<cod_impianto>
									<xsl:value-of select="./rilevazione.codimpianto"/>
								</cod_impianto>
								<superficie>
									<xsl:value-of select="./rilevazione.superifcie"/>
								</superficie>
						<addetti>
									<n>
										<xsl:value-of select="./rilevazione.numero_addetti"/>
									</n>
						</addetti>
						<dipendenti>
									<n>
										<xsl:value-of select="./rilevazione.numero_dipendenti"/>
									</n>
						</dipendenti>
								<tipologia>
									<xsl:value-of select="./rilevazione.tipologia"/>
								</tipologia>
								<att_commerciali>
									<xsl:value-of select="./rilevazione.att_commericale"/>
								</att_commerciali>
								<autolavaggio>
									<xsl:value-of select="./rilevazione.autolavaggio"/>
								</autolavaggio>
								<carburanti_disponibili>
								  <carburantedisponibile>
									<gpl>
										<serbatoio>
											<xsl:if test="./rilevazione_has_carburante.carburante = 'gpl' ">
												<xsl:value-of select="./rilevazione_has_carburante.carburante.serbatoio"/>
											</xsl:if>
											<xsl:if test="./rilevazione_has_carburante.carburante != 'gpl' ">0</xsl:if>										
										</serbatoio>
									</gpl>
									<benzina>
										<serbatoio>
											<xsl:if test="./rilevazione_has_carburante.carburante = 'benzina' ">
												<xsl:value-of select="./rilevazione_has_carburante.serbatoio"/>
											</xsl:if>
											<xsl:if test="./rilevazione_has_carburante.carburante != 'benzina' ">0	</xsl:if>										
										</serbatoio>
									</benzina>
									<gasolio>
										<serbatoio>
											<xsl:if test="./rilevazione_has_carburante.carburante = 'gasolio' ">
												<xsl:value-of select="./rilevazione_has_carburante.serbatoio"/>
											</xsl:if>
											<xsl:if test="./rilevazione_has_carburante.carburante != 'gasolio' ">0</xsl:if>										
										</serbatoio>
									</gasolio>
									<metano>
										<serbatoio>
											<xsl:if test="./rilevazione_has_carburante.carburante = 'metano' ">
												<xsl:value-of select="./rilevazione_has_carburante.serbatoio"/>
											</xsl:if>
											<xsl:if test="./rilevazione_has_carburante.carburante != 'metano' ">0</xsl:if>										
										</serbatoio>
									</metano>
								  </carburantedisponibile>
								</carburanti_disponibili>
								<officine_disponibili>
								  <officina><xsl:value-of select="./rilevazione.officina"/></officina>
								</officine_disponibili>
								<pagamenti_disponibili>
								  <pagamento><xsl:value-of select="./rilevazione_has_pagamento.pagamento"/></pagamento>
								</pagamenti_disponibili>
								<servizi_accessori>
                                      <servizioaccessorio><xsl:value-of select="./rilevazione_has_servizioaccessorio.servizioaccessorio"/></servizioaccessorio>
                                </servizi_accessori>
                                 <servizi>
                     <servizio><xsl:value-of select="./rilevazione_has_servizio.servizio"/></servizio>
                  </servizi>
								<self_service>
									<xsl:value-of select="./rilevazione.self_services"/>
								</self_service>
								<stato>
									<xsl:value-of select="./rilevazione.stato"/>
								</stato>
								<xsl:if test="./rilevazione.bandiera = 'anonimo' ">
									<bandiera><anonimo></anonimo></bandiera>								
								</xsl:if>
								<xsl:if test="./rilevazione.bandiera = 'non_rilevato' ">
									<bandiera><non_rilevato></non_rilevato></bandiera>								
								</xsl:if>
								<xsl:if test="(./rilevazione.bandiera != 'non_rilevato') and (./rilevazione.bandiera != 'anonimo') ">
									<bandiera><marchio>
									<nome>
									<xsl:value-of select="./rilevazione.bandiera"/>
									</nome></marchio>
									</bandiera>								
								</xsl:if>
					</rilevazioneitem>
					</xsl:for-each>
				</rilevazionitype>
			</rilevazioniXML>
		</getRilevazioni>
	</xsl:template>
</xsl:stylesheet>
