package it.unibas.freesbeesla.tracciatura.modello.map;

import java.util.Date;
import java.math.BigDecimal;

import org.apache.torque.Torque;
import org.apache.torque.TorqueException;
import org.apache.torque.map.MapBuilder;
import org.apache.torque.map.DatabaseMap;
import org.apache.torque.map.TableMap;

/**
  *  This class was autogenerated by Torque on:
  *
  * [Tue Dec 14 20:27:47 CET 2010]
  *
  */
public class SlaObjectTraceMapBuilder implements MapBuilder
{
    /**
     * The name of this class
     */
    public static final String CLASS_NAME =
        "it.unibas.freesbeesla.tracciatura.modello.map.SlaObjectTraceMapBuilder";

    /**
     * The database map.
     */
    private DatabaseMap dbMap = null;

    /**
     * Tells us if this DatabaseMapBuilder is built so that we
     * don't have to re-build it every time.
     *
     * @return true if this DatabaseMapBuilder is built
     */
    public boolean isBuilt()
    {
        return (dbMap != null);
    }

    /**
     * Gets the databasemap this map builder built.
     *
     * @return the databasemap
     */
    public DatabaseMap getDatabaseMap()
    {
        return this.dbMap;
    }

    /**
     * The doBuild() method builds the DatabaseMap
     *
     * @throws TorqueException
     */
    public void doBuild() throws TorqueException
    {
        dbMap = Torque.getDatabaseMap("freesbee_sla");

        dbMap.addTable("icar_inf2_sla_object_trace");
        TableMap tMap = dbMap.getTable("icar_inf2_sla_object_trace");

        tMap.setPrimaryKeyMethod("none");


              tMap.addForeignPrimaryKey(
                "icar_inf2_sla_object_trace.INF2_ID_SERVICE", "" , "icar_inf2_service" ,
                "inf2_id_service");
                    tMap.addForeignPrimaryKey(
                "icar_inf2_sla_object_trace.INF2_ID_INITIATOR", "" , "icar_inf2_service" ,
                "inf2_id_initiator");
                    tMap.addForeignPrimaryKey(
                "icar_inf2_sla_object_trace.INF2_ID_RESPONDER", "" , "icar_inf2_service" ,
                "inf2_id_responder");
                    tMap.addPrimaryKey("icar_inf2_sla_object_trace.INF2_SLA_BASIC_METRIC", "" );
                    tMap.addPrimaryKey("icar_inf2_sla_object_trace.INF2_SLA_BASIC_METRIC_DATA_INSERT", new Date() );
                          tMap.addColumn("icar_inf2_sla_object_trace.INF2_SLA_BASIC_METRIC_VALUE", new Double(0) );
                          tMap.addPrimaryKey("icar_inf2_sla_object_trace.INF2_SLA_BASIC_METRIC_MILLISECONDS_INSERT", new BigDecimal(0) );
          }
}
