package com.ws.aci;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-06-15T00:35:58.077+02:00
 * Generated source version: 2.7.4
 * 
 */
@WebServiceClient(name = "AciWS", 
//                  wsdlLocation = "http://localhost:8080/aciWebService/AciWS?wsdl",
                  wsdlLocation = "http://sp.example.unibas:8080/aciWebService/AciWS?wsdl",
                  targetNamespace = "http://aci.ws.com/") 
public class AciWS_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://aci.ws.com/", "AciWS");
    public final static QName AciWSPort = new QName("http://aci.ws.com/", "AciWSPort");
    static {
        URL url = null;
        try {
//            url = new URL("http://localhost:8080/aciWebService/AciWS?wsdl");
            url = new URL("http://sp.example.unibas:8080/aciWebService/AciWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AciWS_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://sp.example.unibas:8080/aciWebService/AciWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AciWS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AciWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AciWS_Service() throws MalformedURLException {
        super(new URL("http://sp.example.unibas:8080/aciWebService/AciWS?wsdl"), SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AciWS_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AciWS_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AciWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AciWS
     */
    @WebEndpoint(name = "AciWSPort")
    public AciWS getAciWSPort() {
        return super.getPort(AciWSPort, AciWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AciWS
     */
    @WebEndpoint(name = "AciWSPort")
    public AciWS getAciWSPort(WebServiceFeature... features) {
        return super.getPort(AciWSPort, AciWS.class, features);
    }

}
