package com.ws.aci;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-06-15T00:35:58.054+02:00
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://aci.ws.com/", name = "AciWS")
@XmlSeeAlso({ObjectFactory.class})
public interface AciWS {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://aci.ws.com/AciWS/cercaImmatricolazioneRequest", output = "http://aci.ws.com/AciWS/cercaImmatricolazioneResponse")
    @RequestWrapper(localName = "cercaImmatricolazione", targetNamespace = "http://aci.ws.com/", className = "com.ws.aci.CercaImmatricolazione")
    @WebMethod
    @ResponseWrapper(localName = "cercaImmatricolazioneResponse", targetNamespace = "http://aci.ws.com/", className = "com.ws.aci.CercaImmatricolazioneResponse")
    public com.ws.aci.Immatricolazione cercaImmatricolazione(
        @WebParam(name = "targa", targetNamespace = "")
        java.lang.String targa
    );
}
