//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.09.20 at 02:59:44 PM CEST 
//


package it.unibas.freesbee.monitoraggio.calcolo.wsaIcarGuaranteeTerms.type;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for AgreementRoleType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AgreementRoleType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AgreementInitiator"/>
 *     &lt;enumeration value="AgreementResponder"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum AgreementRoleType {

    @XmlEnumValue("AgreementInitiator")
    AGREEMENT_INITIATOR("AgreementInitiator"),
    @XmlEnumValue("AgreementResponder")
    AGREEMENT_RESPONDER("AgreementResponder");
    private final String value;

    AgreementRoleType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AgreementRoleType fromValue(String v) {
        for (AgreementRoleType c: AgreementRoleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
