//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.09.20 at 02:59:44 PM CEST 
//


package it.unibas.freesbee.monitoraggio.calcolo.wsaIcarGuaranteeTerms.type;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;


/**
 * <p>Java class for CompensationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompensationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AssessmentInterval">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice>
 *                     &lt;element name="TimeInterval" type="{http://www.w3.org/2001/XMLSchema}duration"/>
 *                     &lt;element name="Count" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ValueUnit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ValueExpression" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompensationType", namespace = "http://schemas.ggf.org/graap/2007/03/ws-agreement", propOrder = {
    "assessmentInterval",
    "valueUnit",
    "valueExpression"
})
public class CompensationType {

    @XmlElement(name = "AssessmentInterval", namespace = "http://schemas.ggf.org/graap/2007/03/ws-agreement", required = true)
    protected CompensationType.AssessmentInterval assessmentInterval;
    @XmlElement(name = "ValueUnit", namespace = "http://schemas.ggf.org/graap/2007/03/ws-agreement")
    protected String valueUnit;
    @XmlElement(name = "ValueExpression", namespace = "http://schemas.ggf.org/graap/2007/03/ws-agreement", required = true)
    protected Object valueExpression;

    /**
     * Gets the value of the assessmentInterval property.
     * 
     * @return
     *     possible object is
     *     {@link CompensationType.AssessmentInterval }
     *     
     */
    public CompensationType.AssessmentInterval getAssessmentInterval() {
        return assessmentInterval;
    }

    /**
     * Sets the value of the assessmentInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompensationType.AssessmentInterval }
     *     
     */
    public void setAssessmentInterval(CompensationType.AssessmentInterval value) {
        this.assessmentInterval = value;
    }

    /**
     * Gets the value of the valueUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValueUnit() {
        return valueUnit;
    }

    /**
     * Sets the value of the valueUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValueUnit(String value) {
        this.valueUnit = value;
    }

    /**
     * Gets the value of the valueExpression property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getValueExpression() {
        return valueExpression;
    }

    /**
     * Sets the value of the valueExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setValueExpression(Object value) {
        this.valueExpression = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice>
     *           &lt;element name="TimeInterval" type="{http://www.w3.org/2001/XMLSchema}duration"/>
     *           &lt;element name="Count" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "timeInterval",
        "count"
    })
    public static class AssessmentInterval {

        @XmlElement(name = "TimeInterval", namespace = "http://schemas.ggf.org/graap/2007/03/ws-agreement")
        protected Duration timeInterval;
        @XmlElement(name = "Count", namespace = "http://schemas.ggf.org/graap/2007/03/ws-agreement")
        @XmlSchemaType(name = "positiveInteger")
        protected BigInteger count;

        /**
         * Gets the value of the timeInterval property.
         * 
         * @return
         *     possible object is
         *     {@link Duration }
         *     
         */
        public Duration getTimeInterval() {
            return timeInterval;
        }

        /**
         * Sets the value of the timeInterval property.
         * 
         * @param value
         *     allowed object is
         *     {@link Duration }
         *     
         */
        public void setTimeInterval(Duration value) {
            this.timeInterval = value;
        }

        /**
         * Gets the value of the count property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getCount() {
            return count;
        }

        /**
         * Sets the value of the count property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setCount(BigInteger value) {
            this.count = value;
        }

    }

}
