//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.09.20 at 02:59:44 PM CEST 
//


package it.unibas.freesbee.monitoraggio.calcolo.wsaIcarGuaranteeTerms.type;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CustomServiceLevelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomServiceLevelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://schemas.ggf.org/graap/2007/03/ws-agreement}Threshold"/>
 *         &lt;element name="Function" type="{http://schemas.ggf.org/graap/2007/03/ws-agreement}FunctionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomServiceLevelType", namespace = "http://schemas.ggf.org/graap/2007/03/ws-agreement", propOrder = {
    "threshold",
    "function"
})
public class CustomServiceLevelType {

    @XmlElement(name = "Threshold", namespace = "http://schemas.ggf.org/graap/2007/03/ws-agreement", required = true)
    protected Threshold threshold;
    @XmlElement(name = "Function", namespace = "http://schemas.ggf.org/graap/2007/03/ws-agreement", required = true)
    protected FunctionType function;

    /**
     * Gets the value of the threshold property.
     * 
     * @return
     *     possible object is
     *     {@link Threshold }
     *     
     */
    public Threshold getThreshold() {
        return threshold;
    }

    /**
     * Sets the value of the threshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link Threshold }
     *     
     */
    public void setThreshold(Threshold value) {
        this.threshold = value;
    }

    /**
     * Gets the value of the function property.
     * 
     * @return
     *     possible object is
     *     {@link FunctionType }
     *     
     */
    public FunctionType getFunction() {
        return function;
    }

    /**
     * Sets the value of the function property.
     * 
     * @param value
     *     allowed object is
     *     {@link FunctionType }
     *     
     */
    public void setFunction(FunctionType value) {
        this.function = value;
    }

}
