//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.09.20 at 02:59:44 PM CEST 
//


package it.unibas.freesbee.monitoraggio.calcolo.wsaIcarGuaranteeTerms.type;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for IntervalTimeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IntervalTimeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Year"/>
 *     &lt;enumeration value="SixMonths"/>
 *     &lt;enumeration value="ThreeMonths"/>
 *     &lt;enumeration value="Month"/>
 *     &lt;enumeration value="TwoWeeks"/>
 *     &lt;enumeration value="Week"/>
 *     &lt;enumeration value="Day"/>
 *     &lt;enumeration value="SixHours"/>
 *     &lt;enumeration value="Hour"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum IntervalTimeType {

    @XmlEnumValue("Year")
    YEAR("Year"),
    @XmlEnumValue("SixMonths")
    SIX_MONTHS("SixMonths"),
    @XmlEnumValue("ThreeMonths")
    THREE_MONTHS("ThreeMonths"),
    @XmlEnumValue("Month")
    MONTH("Month"),
    @XmlEnumValue("TwoWeeks")
    TWO_WEEKS("TwoWeeks"),
    @XmlEnumValue("Week")
    WEEK("Week"),
    @XmlEnumValue("Day")
    DAY("Day"),
    @XmlEnumValue("SixHours")
    SIX_HOURS("SixHours"),
    @XmlEnumValue("Hour")
    HOUR("Hour");
    private final String value;

    IntervalTimeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IntervalTimeType fromValue(String v) {
        for (IntervalTimeType c: IntervalTimeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
