//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.09.20 at 02:59:44 PM CEST 
//


package it.unibas.freesbee.monitoraggio.calcolo.wsaIcarGuaranteeTerms.type;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for KPITargetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KPITargetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="KPIName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CustomServiceLevel" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KPITargetType", namespace = "http://schemas.ggf.org/graap/2007/03/ws-agreement", propOrder = {
    "kpiName",
    "customServiceLevel"
})
public class KPITargetType {

    @XmlElement(name = "KPIName", namespace = "http://schemas.ggf.org/graap/2007/03/ws-agreement", required = true)
    protected String kpiName;
    @XmlElement(name = "CustomServiceLevel", namespace = "http://schemas.ggf.org/graap/2007/03/ws-agreement", required = true)
    protected Object customServiceLevel;

    /**
     * Gets the value of the kpiName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKPIName() {
        return kpiName;
    }

    /**
     * Sets the value of the kpiName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKPIName(String value) {
        this.kpiName = value;
    }

    /**
     * Gets the value of the customServiceLevel property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getCustomServiceLevel() {
        return customServiceLevel;
    }

    /**
     * Sets the value of the customServiceLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setCustomServiceLevel(Object value) {
        this.customServiceLevel = value;
    }

}
