//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.09.20 at 02:59:44 PM CEST 
//


package it.unibas.freesbee.monitoraggio.calcolo.wsaIcarGuaranteeTerms.type;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PreferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PreferenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="ServiceTermReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Utility" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PreferenceType", namespace = "http://schemas.ggf.org/graap/2007/03/ws-agreement", propOrder = {
    "serviceTermReferenceAndUtility"
})
public class PreferenceType {

    @XmlElements({
        @XmlElement(name = "ServiceTermReference", namespace = "http://schemas.ggf.org/graap/2007/03/ws-agreement", required = true, type = String.class),
        @XmlElement(name = "Utility", namespace = "http://schemas.ggf.org/graap/2007/03/ws-agreement", required = true, type = Float.class)
    })
    protected List<Serializable> serviceTermReferenceAndUtility;

    /**
     * Gets the value of the serviceTermReferenceAndUtility property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serviceTermReferenceAndUtility property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServiceTermReferenceAndUtility().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * {@link Float }
     * 
     * 
     */
    public List<Serializable> getServiceTermReferenceAndUtility() {
        if (serviceTermReferenceAndUtility == null) {
            serviceTermReferenceAndUtility = new ArrayList<Serializable>();
        }
        return this.serviceTermReferenceAndUtility;
    }

}
