//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.09.20 at 02:59:44 PM CEST 
//


package it.unibas.freesbee.monitoraggio.calcolo.wsaIcarGuaranteeTerms.type;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceLevelObjectiveType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceLevelObjectiveType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="KPITarget" type="{http://schemas.ggf.org/graap/2007/03/ws-agreement}KPITargetType"/>
 *         &lt;element name="CustomServiceLevel" type="{http://schemas.ggf.org/graap/2007/03/ws-agreement}CustomServiceLevelType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceLevelObjectiveType", namespace = "http://schemas.ggf.org/graap/2007/03/ws-agreement", propOrder = {
    "kpiTarget",
    "customServiceLevel"
})
public class ServiceLevelObjectiveType {

    @XmlElement(name = "KPITarget", namespace = "http://schemas.ggf.org/graap/2007/03/ws-agreement")
    protected KPITargetType kpiTarget;
    @XmlElement(name = "CustomServiceLevel", namespace = "http://schemas.ggf.org/graap/2007/03/ws-agreement")
    protected CustomServiceLevelType customServiceLevel;

    /**
     * Gets the value of the kpiTarget property.
     * 
     * @return
     *     possible object is
     *     {@link KPITargetType }
     *     
     */
    public KPITargetType getKPITarget() {
        return kpiTarget;
    }

    /**
     * Sets the value of the kpiTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link KPITargetType }
     *     
     */
    public void setKPITarget(KPITargetType value) {
        this.kpiTarget = value;
    }

    /**
     * Gets the value of the customServiceLevel property.
     * 
     * @return
     *     possible object is
     *     {@link CustomServiceLevelType }
     *     
     */
    public CustomServiceLevelType getCustomServiceLevel() {
        return customServiceLevel;
    }

    /**
     * Sets the value of the customServiceLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomServiceLevelType }
     *     
     */
    public void setCustomServiceLevel(CustomServiceLevelType value) {
        this.customServiceLevel = value;
    }

}
