//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.09.20 at 02:59:44 PM CEST 
//


package it.unibas.freesbee.monitoraggio.calcolo.wsaIcarGuaranteeTerms.type;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServicePropertiesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServicePropertiesType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.ggf.org/graap/2007/03/ws-agreement}ServiceTermType">
 *       &lt;sequence>
 *         &lt;element name="VariableSet" type="{http://schemas.ggf.org/graap/2007/03/ws-agreement}VariableSetType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServicePropertiesType", namespace = "http://schemas.ggf.org/graap/2007/03/ws-agreement", propOrder = {
    "variableSet"
})
public class ServicePropertiesType
    extends ServiceTermType
{

    @XmlElement(name = "VariableSet", namespace = "http://schemas.ggf.org/graap/2007/03/ws-agreement", required = true)
    protected VariableSetType variableSet;

    /**
     * Gets the value of the variableSet property.
     * 
     * @return
     *     possible object is
     *     {@link VariableSetType }
     *     
     */
    public VariableSetType getVariableSet() {
        return variableSet;
    }

    /**
     * Sets the value of the variableSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariableSetType }
     *     
     */
    public void setVariableSet(VariableSetType value) {
        this.variableSet = value;
    }

}
