//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.09.20 at 02:59:44 PM CEST 
//


package it.unibas.freesbee.monitoraggio.calcolo.wsaIcarGuaranteeTerms.type;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="Interval" type="{http://schemas.ggf.org/graap/2007/03/ws-agreement}IntervalTimeType"/>
 *         &lt;element name="Times" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "interval",
    "times"
})
@XmlRootElement(name = "Window", namespace = "http://schemas.ggf.org/graap/2007/03/ws-agreement")
public class Window {

    @XmlElement(name = "Interval", namespace = "http://schemas.ggf.org/graap/2007/03/ws-agreement")
    protected IntervalTimeType interval;
    @XmlElement(name = "Times", namespace = "http://schemas.ggf.org/graap/2007/03/ws-agreement")
    protected Long times;

    /**
     * Gets the value of the interval property.
     * 
     * @return
     *     possible object is
     *     {@link IntervalTimeType }
     *     
     */
    public IntervalTimeType getInterval() {
        return interval;
    }

    /**
     * Sets the value of the interval property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntervalTimeType }
     *     
     */
    public void setInterval(IntervalTimeType value) {
        this.interval = value;
    }

    /**
     * Gets the value of the times property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTimes() {
        return times;
    }

    /**
     * Sets the value of the times property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTimes(Long value) {
        this.times = value;
    }

}
