package it.unibas.freesbeesp.test;

import it.unibas.icar.freesbeesp.sso.CredentialUtil;
import java.util.Iterator;
import junit.framework.TestCase;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.jsoup.Jsoup;
import org.jsoup.select.Elements;
import org.opensaml.xml.signature.Signature;

public class TestHtmlLoginIbasho extends TestCase {

    private static Log logger = LogFactory.getLog(TestHtmlLoginIbasho.class);

    private String xmlString = "<html lang=\"it\">\n"
            + "    <head>\n"
            + "        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\n"
            + "        <meta name=\"description\" content=\"Accesso sistema di identita' regionale\"/>\n"
            + "        <link rel=\"icon\" type=\"image/ico\" href=\"http://www.regione.basilicata.it/giunta/css/favicon/logo.ico\"/>\n"
            + "        <title>Ibasho Identity Provider Login</title>\n"
            + "\n"
            + "        <link rel=\"stylesheet\" type=\"text/css\" href=\"/ibasho_idp/css/default.css\" />\n"
            + "\n"
            + "\n"
            + "        <script type=\"text/javascript\">\n"
            + "            var goValue;\n"
            + "\n"
            + "            var _gaq = _gaq || [];\n"
            + "            _gaq.push(['_setAccount', 'UA-12411699-6']);\n"
            + "            _gaq.push(['_trackPageview']);\n"
            + "\n"
            + "            (function() {\n"
            + "                var ga = document.createElement('script');\n"
            + "                ga.type = 'text/javascript';\n"
            + "                ga.async = true;\n"
            + "                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';\n"
            + "                var s = document.getElementsByTagName('script')[0];\n"
            + "                s.parentNode.insertBefore(ga, s);\n"
            + "            })();\n"
            + "\n"
            + "\n"
            + "            function mcfocus() {\n"
            + "                var size = 8;\n"
            + "                for (var i = 0; i < size; i++) {\n"
            + "                    var obj = document.getElementById(\"code_\" + i);\n"
            + "                    if (!obj.disabled) {\n"
            + "                        if (obj.value == '') {\n"
            + "                            obj.focus();\n"
            + "                            break;\n"
            + "                        }\n"
            + "                    }\n"
            + "                }\n"
            + "            }\n"
            + "\n"
            + "            function browser() {\n"
            + "                var nAgt = navigator.userAgent;\n"
            + "                var browserName = navigator.appName;\n"
            + "                var nameOffset, verOffset;\n"
            + "\n"
            + "                goValue = 0;\n"
            + "                if ((verOffset = nAgt.indexOf(\"MSIE\")) != -1) {\n"
            + "                    browserName = \"Microsoft Internet Explorer\";\n"
            + "                    goValue = -3;\n"
            + "                }\n"
            + "                else if ((verOffset = nAgt.indexOf(\"Opera\")) != -1) {\n"
            + "                    browserName = \"Opera\";\n"
            + "                    goValue = -1;\n"
            + "                }\n"
            + "                else if ((verOffset = nAgt.indexOf(\"Chrome\")) != -1) {\n"
            + "                    browserName = \"Chrome\";\n"
            + "                    //goValue=-1;\n"
            + "                    goValue = -2;\n"
            + "                }\n"
            + "                else if ((verOffset = nAgt.indexOf(\"Safari\")) != -1) {\n"
            + "                    browserName = \"Safari\";\n"
            + "                    goValue = -2;\n"
            + "                }\n"
            + "                else if ((verOffset = nAgt.indexOf(\"Firefox\")) != -1) {\n"
            + "                    browserName = \"Firefox\";\n"
            + "                    goValue = -3;\n"
            + "                }\n"
            + "                else if ((nameOffset = nAgt.lastIndexOf(' ') + 1) < (verOffset = nAgt.lastIndexOf('/')))\n"
            + "                {\n"
            + "                    browserName = nAgt.substring(nameOffset, verOffset);\n"
            + "                    if (browserName.toLowerCase() == browserName.toUpperCase()) {\n"
            + "                        browserName = navigator.appName;\n"
            + "                    }\n"
            + "                    goValue = -1;\n"
            + "                }\n"
            + "\n"
            + "                var numberofvisited = history.length;\n"
            + "                var text = 'Browser name  = ' + browserName + '<br>';\n"
            + "                text = text + \"Referer:  \" + document.referrer + \"<br/>\";\n"
            + "                text = text + \"The number of pages visited in this window is \" + numberofvisited + \" pages.<br/>\";\n"
            + "                text = text + \"<input type='button' value='Press the Button to go to Page \" + goValue + \"!!!' onclick='window.history.go(\" + goValue + \")' /><br/>\";\n"
            + "                //document.getElementById(\"browser-div\").innerHTML = text;\n"
            + "            }\n"
            + "\n"
            + "        </script>\n"
            + "    </head>\n"
            + "    <body onload=\"browser();\">\n"
            + "\n"
            + "        <div class=\"wrapper\">\n"
            + "\n"
            + "            <div class=\"header-box-regbas\"></div>\n"
            + "\n"
            + "            <div class=\"content\">\n"
            + "                <div class=\"left-box\">\n"
            + "                    <div class=\"login-box\">\n"
            + "                        <h2 class=\"noDisplay\">\n"
            + "                            <span class=\"left\">Accedi</span>\n"
            + "                            <span class=\"right\">\n"
            + "                                <a class=\"default-button button-orange\" href=\"https://ibasho.basilicatanet.it/profile/cprofile\">\n"
            + "                                    Non sono registrato\n"
            + "                                </a>\n"
            + "                            </span>\n"
            + "                        </h2>\n"
            + "\n"
            + "                        <form class=\"login-form first-box\" method=\"post\" action=\"shibb/ssosc\">\n"
            + "                            <input type=\"hidden\" name=\"PROVIDER_ID\" value=\"freesbeesp-guard\" />\n"
            + "                            <input type=\"hidden\" name=\"ASSERTION_CONSUMER_SERVICE_URL\" value=\"http://iff.regione.basilicata.it/Shibboleth.sso/SAML2/POST\" />\n"
            + "                            <input type=\"hidden\" name=\"guanxi:mode\" value=\"sc_authenticate\" />\n"
            + "\n"
            + "                            <input type=\"hidden\" name=\"SAMLRequest\" value=\"fZHLboMwEEV/BXkPBvJQYgUkmiwaKW1QoF10ExkYgiWwqcf08fc1oZXSTRbe2HeOfY83yLu2Z8lgGnmC9wHQOF9dK5FdDyIyaMkUR4FM8g6QmZJlydOBhZ7Peq2MKlVLnAQRtBFKbpXEoQOdgf4QJbycDhFpjOkZpaKuPQ0XGwKvsMRWlNxwTxiaNaIoVAum8RAVHfkhTY9ZTpydfZCQfERPIBxJdrxRNxAJZuRM+2dR9TTLjsTZ7yJyLmeLqvBLvgjXYTEPOKyCesXDZR0EvFiVaxtDHGAv0XJMREI/mLv+0g0Xub9m84DNwjfipL9VH4SshLzc91JMIWSPeZ66U5FX0HgtYQMk3ox22fVifeP7Ppb/SSZxrQGwsKt3LwPX1YbeACd6z54tYb9LlXX07SRtqz63GriBiASExtPI/6+PfwA=\" />\n"
            + "\n"
            + "                            <input type=\"hidden\" name=\"RelayState\" value=\"cookie:1403689292_92c3\" />\n"
            + "\n"
            + "                            <input type=\"submit\" class=\"default-button button-green submitSmart\" name=\"submit\" id=\"submit\" value=\"Accedi\"/>\n"
            + "                            <a class=\"help\"  href=\"/ibasho_idp/_files/firefox.pdf\">Configura certificati con Mozilla Firefox: clicca qui</a>\n"
            + "                        </form>\n"
            + "\n"
            + "                        <form class=\"login-form second-box\" method=\"post\" action=\"shibb/sso\">\n"
            + "\n"
            + "                            <label class=\"first-label\">\n"
            + "                                <strong class=\"label\">Nome utente <span class=\"example\">&nbsp;&nbsp; (es. mario.rossi)</span></strong>\n"
            + "                                <input type=\"text\" name=\"userid\" id=\"userid\"/>\n"
            + "                            </label>\n"
            + "                            <label class=\"second-label\">\n"
            + "                                <strong class=\"label\">Password</strong>\n"
            + "                                <input type=\"password\" name=\"password\" id=\"password\"/>\n"
            + "                            </label>\n"
            + "\n"
            + "\n"
            + "\n"
            + "                            <input type=\"hidden\" name=\"guanxi:mode\" value=\"authenticate\" />\n"
            + "                            <input type=\"submit\" class=\"default-button button-green submitUsername\" name=\"submit\" id=\"submit\" value=\"Accedi\"/>\n"
            + "                            <label class=\"forgot\">\n"
            + "                                <a href=\"https://ibasho.basilicatanet.it/profile/user/recovery\" target=\"_blank\">\n"
            + "                                    Hai smarrito le tue credenziali?\n"
            + "                                </a>\n"
            + "                                <br/>\n"
            + "                                <a class=\"back\" href=\"#\" onclick=\"window.history.go(goValue)\">\n"
            + "                                    Torna indietro\n"
            + "                                </a>\n"
            + "                            </label>\n"
            + "                            <label class=\"register\">\n"
            + "                                <a href=\"https://ibasho.basilicatanet.it/profile/cprofile\">registrati</a>\n"
            + "                            </label>\n"
            + "                            <!--label class=\"back\">\n"
            + "                                <a href=\"#\" onclick=\"window.history.go(goValue)\">\n"
            + "                                    Torna indietro\n"
            + "                                </a>\n"
            + "                            </label-->\n"
            + "\n"
            + "                            <input type=\"hidden\" name=\"SAMLRequest\" value=\"fZHLboMwEEV/BXkPBvJQYgUkmiwaKW1QoF10ExkYgiWwqcf08fc1oZXSTRbe2HeOfY83yLu2Z8lgGnmC9wHQOF9dK5FdDyIyaMkUR4FM8g6QmZJlydOBhZ7Peq2MKlVLnAQRtBFKbpXEoQOdgf4QJbycDhFpjOkZpaKuPQ0XGwKvsMRWlNxwTxiaNaIoVAum8RAVHfkhTY9ZTpydfZCQfERPIBxJdrxRNxAJZuRM+2dR9TTLjsTZ7yJyLmeLqvBLvgjXYTEPOKyCesXDZR0EvFiVaxtDHGAv0XJMREI/mLv+0g0Xub9m84DNwjfipL9VH4SshLzc91JMIWSPeZ66U5FX0HgtYQMk3ox22fVifeP7Ppb/SSZxrQGwsKt3LwPX1YbeACd6z54tYb9LlXX07SRtqz63GriBiASExtPI/6+PfwA=\" />\n"
            + "\n"
            + "                            <input type=\"hidden\" name=\"RelayState\" value=\"cookie:1403689292_92c3\" />\n"
            + "\n"
            + "                            <br />\n"
            + "\n"
            + "\n"
            + "                        </form>\n"
            + "                        <div style=\"clear: both;\"></div>\n"
            + "                    </div>\n"
            + "\n"
            + "                </div>\n"
            + "                <div class=\"right-box\">\n"
            + "                    <br/>\n"
            + "                    <div>\n"
            + "                        <h2>Una password per accedere a tutti i <a class=\"link\" href=\"http://servizi.basilicatanet.it\" target=\"_blank\">servizi</a>.</h2>\n"
            + "                    </div>\n"
            + "                    <ul class=\"info\">\n"
            + "                        <li>\n"
            + "                            <img src=\"/ibasho_idp/css/images/users.png\" alt=\"\"/>\n"
            + "                            <p class=\"title\">Identity management system (IMS)</p>\n"
            + "                            <p>\n"
            + "                                L'IMS &egrave; un sistema di autenticazione unica, un sistema specializzato\n"
            + "                                che permette ad un utente di autenticarsi una sola volta e di poter\n"
            + "                                accedere poi a tutte le risorse informatiche alle quali &egrave; abilitato.\n"
            + "                                Il vantaggio principale di questo sistema &egrave; quello di semplificare\n"
            + "                                la gestione delle password.\n"
            + "                            </p>\n"
            + "                        </li>\n"
            + "                        <li>\n"
            + "                            <img src=\"/ibasho_idp/css/images/pin.png\" alt=\"\"/>\n"
            + "                            <p class=\"title\">Personal Identification Number (PIN)</p>\n"
            + "                            <p>Richiedi il PIN per l'accesso ai servizi che richiedono una autenticazione forte.\n"
            + "                                Per richiedere il tuo PIN, dopo aver effettuato la classica procedura di registrazione,\n"
            + "                                collegati alla tua <a href=\"https://ibasho.basilicatanet.it/IbashoMyPage\" target=\"_blank\">pagina personale</a>\n"
            + "                                oppure <a href=\"http://richieste.regione.basilicata.it/pin\" target=\"_blank\">clicca qui</a>.</p>\n"
            + "                        </li>\n"
            + "                        <li>\n"
            + "                            <img src=\"/ibasho_idp/css/images/phone.png\" alt=\"\"/>\n"
            + "                            <p class=\"title\">Accesso tramite smartphone</p>\n"
            + "                            <p>Per accedere dal tuo cellulare, apri il browser web del cellulare alla pagina <b>https://ibasho.basilicatanet.it/IbashoMyPage</b>.\n"
            + "                                Prima, per&ograve;, ricordati di richiedere il PIN per l'accesso ai servizi, servir&agrave; anche per l'accesso tramite smartphone.</p>\n"
            + "                        </li>\n"
            + "                    </ul>\n"
            + "                </div>\n"
            + "            </div>\n"
            + "            <div class=\"footer-box\">\n"
            + "                <div class=\"footer footer-content\">\n"
            + "                    <ul>\n"
            + "                        <li class=\"img\">\n"
            + "                            <a class=\"img\" href=\"http://www.pofesr.basilicata.it/\" target=\"_blank\">\n"
            + "                                <img src=\"/ibasho_idp/css/images/fesr.png\" alt=\"FESR\" />\n"
            + "                            </a>\n"
            + "                        </li>\n"
            + "                        <li>&copy; 2010 Regione Basilicata</li>\n"
            + "                        <li><a href=\"http://www.basilicatanet.it\" target=\"_blank\">Basilicatanet</a></li>\n"
            + "                        <li><a href=\"http://www.regione.basilicata.it\" target=\"_blank\">Regione Basilicata</a></li>\n"
            + "                        <li><a href=\"http://java.com/\">Scarica Java</a></li>\n"
            + "                        <li>\n"
            + "                            <!--script type=\"text/javascript\" src=\"https://seal.verisign.com/getseal?host_name=ibasho.basilicatanet.it&size=S&use_flash=NO&use_transparent=NO&lang=it\"></script-->\n"
            + "                            <a href=\"http://www.verisign.com/products-services/security-services/ssl/ssl-information-center/\"\n"
            + "                               target=\"_blank\">Informazioni sui certificati SSL</a>\n"
            + "                        </li>\n"
            + "                        <li><a href=\"mailto:ims@regione.basilicata.it\">Supporto</a></li>\n"
            + "\n"
            + "                    </ul>\n"
            + "                </div>\n"
            + "            </div>\n"
            + "        </div>\n"
            + "\n"
            + "    </body>\n"
            + "</html>";

//    public void test1() throws Exception {
//        int start = xmlString.lastIndexOf("<form");
//        int end = xmlString.lastIndexOf("</form>");
//
//        String cleanDocument = xmlString.substring(start, end + 7);
//
//        cleanDocument = cleanDocument.replace("&nbsp;", "");
//        org.jsoup.nodes.Document document = Jsoup.parse(cleanDocument);
//        Elements inputs = document.select("input");
//        Iterator<org.jsoup.nodes.Element> iterator = inputs.iterator();
//        while(iterator.hasNext()) {
//            org.jsoup.nodes.Element input = iterator.next();
//            if(input.attr("name").equals("SAMLRequest")) {
//                System.out.println(input.attr("value"));
//            }
//            if(input.attr("name").equals("RelayState")) {
//                System.out.println(input.attr("value"));
//            }
//        }
//    }
        

}
