package it.unibas.icar.freesbee.ws.client.autenticazione.cxf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-05-30T22:12:29.953+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "WSAutenticazioneImplService", 
                  wsdlLocation = "http://localhost:8191/ws/autenticazione?wsdl",
                  targetNamespace = "http://web.ws.freesbee.icar.unibas.it/") 
public class WSAutenticazioneImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://web.ws.freesbee.icar.unibas.it/", "WSAutenticazioneImplService");
    public final static QName WSAutenticazioneImplPort = new QName("http://web.ws.freesbee.icar.unibas.it/", "WSAutenticazioneImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8191/ws/autenticazione?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSAutenticazioneImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8191/ws/autenticazione?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSAutenticazioneImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSAutenticazioneImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSAutenticazioneImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSAutenticazioneImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSAutenticazioneImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSAutenticazioneImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns IWSAutenticazione
     */
    @WebEndpoint(name = "WSAutenticazioneImplPort")
    public IWSAutenticazione getWSAutenticazioneImplPort() {
        return super.getPort(WSAutenticazioneImplPort, IWSAutenticazione.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWSAutenticazione
     */
    @WebEndpoint(name = "WSAutenticazioneImplPort")
    public IWSAutenticazione getWSAutenticazioneImplPort(WebServiceFeature... features) {
        return super.getPort(WSAutenticazioneImplPort, IWSAutenticazione.class, features);
    }

}
