package com.ws.comune;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-06-15T17:27:07.884+02:00
 * Generated source version: 2.7.4
 * 
 */
@WebServiceClient(name = "ComuneWS", 
//                  wsdlLocation = "http://localhost:8080/comuneWSApplication/ComuneWS?wsdl",
                  wsdlLocation = "http://sp.example.unibas:8080/comuneWSApplication/ComuneWS?wsdl",
                  targetNamespace = "http://comune.ws.com/") 
public class ComuneWS_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://comune.ws.com/", "ComuneWS");
    public final static QName ComuneWSPort = new QName("http://comune.ws.com/", "ComuneWSPort");
    static {
        URL url = null;
        try {
//            url = new URL("http://localhost:8080/comuneWSApplication/ComuneWS?wsdl");
            url = new URL("http://sp.example.unibas:8080/comuneWSApplication/ComuneWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ComuneWS_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://sp.example.unibas:8080/comuneWSApplication/ComuneWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ComuneWS_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ComuneWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ComuneWS_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ComuneWS_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ComuneWS_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ComuneWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ComuneWS
     */
    @WebEndpoint(name = "ComuneWSPort")
    public ComuneWS getComuneWSPort() {
        return super.getPort(ComuneWSPort, ComuneWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ComuneWS
     */
    @WebEndpoint(name = "ComuneWSPort")
    public ComuneWS getComuneWSPort(WebServiceFeature... features) {
        return super.getPort(ComuneWSPort, ComuneWS.class, features);
    }

}
