package it.unibas.icar.freesbee.ws.registroservizi.client.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-12-18T14:05:48.943+01:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://icar.unibas.it/freesbee/", name = "IWSRegistroServizi")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IWSRegistroServizi {

    @WebResult(name = "getFruitoreServizioSpcoopResponse", targetNamespace = "http://icar.unibas.it/freesbee/", partName = "parameters")
    @WebMethod
    public GetFruitoreServizioSpcoopResponse getFruitoreServizioSpcoop(
        @WebParam(partName = "parameters", name = "getFruitoreServizioSpcoop", targetNamespace = "http://icar.unibas.it/freesbee/")
        GetFruitoreServizioSpcoop parameters,
        @WebParam(partName = "indirizzoRegistro", name = "indirizzoRegistro", targetNamespace = "http://icar.unibas.it/freesbee/", header = true)
        java.lang.String indirizzoRegistro
    ) throws SOAPFault_Exception, DAOException_Exception;

    @WebResult(name = "getFruitoriServizioSpcoopCorrelatoResponse", targetNamespace = "http://icar.unibas.it/freesbee/", partName = "parameters")
    @WebMethod
    public GetFruitoriServizioSpcoopCorrelatoResponse getFruitoriServizioSpcoopCorrelato(
        @WebParam(partName = "parameters", name = "getFruitoriServizioSpcoopCorrelato", targetNamespace = "http://icar.unibas.it/freesbee/")
        GetFruitoriServizioSpcoopCorrelato parameters,
        @WebParam(partName = "indirizzoRegistro", name = "indirizzoRegistro", targetNamespace = "http://icar.unibas.it/freesbee/", header = true)
        java.lang.String indirizzoRegistro
    ) throws SOAPFault_Exception, DAOException_Exception;

    @WebResult(name = "getAllIdSoggettiSPCoopResponse", targetNamespace = "http://icar.unibas.it/freesbee/", partName = "parameters")
    @WebMethod
    public GetAllIdSoggettiSPCoopResponse getAllIdSoggettiSPCoop(
        @WebParam(partName = "parameters", name = "getAllIdSoggettiSPCoop", targetNamespace = "http://icar.unibas.it/freesbee/")
        GetAllIdSoggettiSPCoop parameters,
        @WebParam(partName = "indirizzoRegistro", name = "indirizzoRegistro", targetNamespace = "http://icar.unibas.it/freesbee/", header = true)
        java.lang.String indirizzoRegistro
    ) throws SOAPFault_Exception, DAOException_Exception;

    @WebResult(name = "getServizioSPCoopCorrelatoResponse", targetNamespace = "http://icar.unibas.it/freesbee/", partName = "parameters")
    @WebMethod
    public GetServizioSPCoopCorrelatoResponse getServizioSPCoopCorrelato(
        @WebParam(partName = "parameters", name = "getServizioSPCoopCorrelato", targetNamespace = "http://icar.unibas.it/freesbee/")
        GetServizioSPCoopCorrelato parameters,
        @WebParam(partName = "indirizzoRegistro", name = "indirizzoRegistro", targetNamespace = "http://icar.unibas.it/freesbee/", header = true)
        java.lang.String indirizzoRegistro
    ) throws SOAPFault_Exception, DAOException_Exception;

    @WebResult(name = "existsServizioSpcoopResponse", targetNamespace = "http://icar.unibas.it/freesbee/", partName = "parameters")
    @WebMethod
    public ExistsServizioSpcoopResponse existsServizioSpcoop(
        @WebParam(partName = "parameters", name = "existsServizioSpcoop", targetNamespace = "http://icar.unibas.it/freesbee/")
        ExistsServizioSpcoop parameters,
        @WebParam(partName = "indirizzoRegistro", name = "indirizzoRegistro", targetNamespace = "http://icar.unibas.it/freesbee/", header = true)
        java.lang.String indirizzoRegistro
    ) throws SOAPFault_Exception, DAOException_Exception;

    @WebResult(name = "getAllIdServiziSPCoopCorrelatiResponse", targetNamespace = "http://icar.unibas.it/freesbee/", partName = "parameters")
    @WebMethod
    public GetAllIdServiziSPCoopCorrelatiResponse getAllIdServiziSPCoopCorrelati(
        @WebParam(partName = "parameters", name = "getAllIdServiziSPCoopCorrelati", targetNamespace = "http://icar.unibas.it/freesbee/")
        GetAllIdServiziSPCoopCorrelati parameters,
        @WebParam(partName = "indirizzoRegistro", name = "indirizzoRegistro", targetNamespace = "http://icar.unibas.it/freesbee/", header = true)
        java.lang.String indirizzoRegistro
    ) throws SOAPFault_Exception, DAOException_Exception;

    @WebResult(name = "existsAccordoServizioResponse", targetNamespace = "http://icar.unibas.it/freesbee/", partName = "parameters")
    @WebMethod
    public ExistsAccordoServizioResponse existsAccordoServizio(
        @WebParam(partName = "parameters", name = "existsAccordoServizio", targetNamespace = "http://icar.unibas.it/freesbee/")
        ExistsAccordoServizio parameters,
        @WebParam(partName = "indirizzoRegistro", name = "indirizzoRegistro", targetNamespace = "http://icar.unibas.it/freesbee/", header = true)
        java.lang.String indirizzoRegistro
    ) throws SOAPFault_Exception, DAOException_Exception;

    @WebResult(name = "getAllIdServiziSPCoopResponse", targetNamespace = "http://icar.unibas.it/freesbee/", partName = "parameters")
    @WebMethod
    public GetAllIdServiziSPCoopResponse getAllIdServiziSPCoop(
        @WebParam(partName = "parameters", name = "getAllIdServiziSPCoop", targetNamespace = "http://icar.unibas.it/freesbee/")
        GetAllIdServiziSPCoop parameters,
        @WebParam(partName = "indirizzoRegistro", name = "indirizzoRegistro", targetNamespace = "http://icar.unibas.it/freesbee/", header = true)
        java.lang.String indirizzoRegistro
    ) throws SOAPFault_Exception, DAOException_Exception;

    @WebResult(name = "existsServizioSpcoopCorrelatoResponse", targetNamespace = "http://icar.unibas.it/freesbee/", partName = "parameters")
    @WebMethod
    public ExistsServizioSpcoopCorrelatoResponse existsServizioSpcoopCorrelato(
        @WebParam(partName = "parameters", name = "existsServizioSpcoopCorrelato", targetNamespace = "http://icar.unibas.it/freesbee/")
        ExistsServizioSpcoopCorrelato parameters,
        @WebParam(partName = "indirizzoRegistro", name = "indirizzoRegistro", targetNamespace = "http://icar.unibas.it/freesbee/", header = true)
        java.lang.String indirizzoRegistro
    ) throws SOAPFault_Exception, DAOException_Exception;

    @WebResult(name = "existsFruitoreServizioSpcoopCorrelatoResponse", targetNamespace = "http://icar.unibas.it/freesbee/", partName = "parameters")
    @WebMethod
    public ExistsFruitoreServizioSpcoopCorrelatoResponse existsFruitoreServizioSpcoopCorrelato(
        @WebParam(partName = "parameters", name = "existsFruitoreServizioSpcoopCorrelato", targetNamespace = "http://icar.unibas.it/freesbee/")
        ExistsFruitoreServizioSpcoopCorrelato parameters,
        @WebParam(partName = "indirizzoRegistro", name = "indirizzoRegistro", targetNamespace = "http://icar.unibas.it/freesbee/", header = true)
        java.lang.String indirizzoRegistro
    ) throws SOAPFault_Exception, DAOException_Exception;

    @WebResult(name = "getAccordoServizioResponse", targetNamespace = "http://icar.unibas.it/freesbee/", partName = "parameters")
    @WebMethod
    public GetAccordoServizioResponse getAccordoServizio(
        @WebParam(partName = "parameters", name = "getAccordoServizio", targetNamespace = "http://icar.unibas.it/freesbee/")
        GetAccordoServizio parameters,
        @WebParam(partName = "indirizzoRegistro", name = "indirizzoRegistro", targetNamespace = "http://icar.unibas.it/freesbee/", header = true)
        java.lang.String indirizzoRegistro
    ) throws SOAPFault_Exception, DAOException_Exception;

    @WebResult(name = "getAllIdAccordiServizioResponse", targetNamespace = "http://icar.unibas.it/freesbee/", partName = "parameters")
    @WebMethod
    public GetAllIdAccordiServizioResponse getAllIdAccordiServizio(
        @WebParam(partName = "parameters", name = "getAllIdAccordiServizio", targetNamespace = "http://icar.unibas.it/freesbee/")
        GetAllIdAccordiServizio parameters,
        @WebParam(partName = "indirizzoRegistro", name = "indirizzoRegistro", targetNamespace = "http://icar.unibas.it/freesbee/", header = true)
        java.lang.String indirizzoRegistro
    ) throws SOAPFault_Exception, DAOException_Exception;

    @WebResult(name = "getServizioSPCoopCorrelatoByAccordoResponse", targetNamespace = "http://icar.unibas.it/freesbee/", partName = "parameters")
    @WebMethod
    public GetServizioSPCoopCorrelatoByAccordoResponse getServizioSPCoopCorrelatoByAccordo(
        @WebParam(partName = "parameters", name = "getServizioSPCoopCorrelatoByAccordo", targetNamespace = "http://icar.unibas.it/freesbee/")
        GetServizioSPCoopCorrelatoByAccordo parameters,
        @WebParam(partName = "indirizzoRegistro", name = "indirizzoRegistro", targetNamespace = "http://icar.unibas.it/freesbee/", header = true)
        java.lang.String indirizzoRegistro
    ) throws SOAPFault_Exception, DAOException_Exception;

    @WebResult(name = "getFruitoriServizioSpcoopResponse", targetNamespace = "http://icar.unibas.it/freesbee/", partName = "parameters")
    @WebMethod
    public GetFruitoriServizioSpcoopResponse getFruitoriServizioSpcoop(
        @WebParam(partName = "parameters", name = "getFruitoriServizioSpcoop", targetNamespace = "http://icar.unibas.it/freesbee/")
        GetFruitoriServizioSpcoop parameters,
        @WebParam(partName = "indirizzoRegistro", name = "indirizzoRegistro", targetNamespace = "http://icar.unibas.it/freesbee/", header = true)
        java.lang.String indirizzoRegistro
    ) throws SOAPFault_Exception, DAOException_Exception;

    @WebResult(name = "getServizioSPCoopResponse", targetNamespace = "http://icar.unibas.it/freesbee/", partName = "parameters")
    @WebMethod
    public GetServizioSPCoopResponse getServizioSPCoop(
        @WebParam(partName = "parameters", name = "getServizioSPCoop", targetNamespace = "http://icar.unibas.it/freesbee/")
        GetServizioSPCoop parameters,
        @WebParam(partName = "indirizzoRegistro", name = "indirizzoRegistro", targetNamespace = "http://icar.unibas.it/freesbee/", header = true)
        java.lang.String indirizzoRegistro
    ) throws SOAPFault_Exception, DAOException_Exception;

    @WebResult(name = "getFruitoreServizioSpcoopCorrelatoResponse", targetNamespace = "http://icar.unibas.it/freesbee/", partName = "parameters")
    @WebMethod
    public GetFruitoreServizioSpcoopCorrelatoResponse getFruitoreServizioSpcoopCorrelato(
        @WebParam(partName = "parameters", name = "getFruitoreServizioSpcoopCorrelato", targetNamespace = "http://icar.unibas.it/freesbee/")
        GetFruitoreServizioSpcoopCorrelato parameters,
        @WebParam(partName = "indirizzoRegistro", name = "indirizzoRegistro", targetNamespace = "http://icar.unibas.it/freesbee/", header = true)
        java.lang.String indirizzoRegistro
    ) throws SOAPFault_Exception, DAOException_Exception;

    @WebResult(name = "getSoggettoSPCoopResponse", targetNamespace = "http://icar.unibas.it/freesbee/", partName = "parameters")
    @WebMethod
    public GetSoggettoSPCoopResponse getSoggettoSPCoop(
        @WebParam(partName = "parameters", name = "getSoggettoSPCoop", targetNamespace = "http://icar.unibas.it/freesbee/")
        GetSoggettoSPCoop parameters,
        @WebParam(partName = "indirizzoRegistro", name = "indirizzoRegistro", targetNamespace = "http://icar.unibas.it/freesbee/", header = true)
        java.lang.String indirizzoRegistro
    ) throws SOAPFault_Exception, DAOException_Exception;

    @WebResult(name = "existsFruitoreServizioSpcoopResponse", targetNamespace = "http://icar.unibas.it/freesbee/", partName = "parameters")
    @WebMethod
    public ExistsFruitoreServizioSpcoopResponse existsFruitoreServizioSpcoop(
        @WebParam(partName = "parameters", name = "existsFruitoreServizioSpcoop", targetNamespace = "http://icar.unibas.it/freesbee/")
        ExistsFruitoreServizioSpcoop parameters,
        @WebParam(partName = "indirizzoRegistro", name = "indirizzoRegistro", targetNamespace = "http://icar.unibas.it/freesbee/", header = true)
        java.lang.String indirizzoRegistro
    ) throws SOAPFault_Exception, DAOException_Exception;

    @WebResult(name = "existsSoggettoSPCoopResponse", targetNamespace = "http://icar.unibas.it/freesbee/", partName = "parameters")
    @WebMethod
    public ExistsSoggettoSPCoopResponse existsSoggettoSPCoop(
        @WebParam(partName = "parameters", name = "existsSoggettoSPCoop", targetNamespace = "http://icar.unibas.it/freesbee/")
        ExistsSoggettoSPCoop parameters,
        @WebParam(partName = "indirizzoRegistro", name = "indirizzoRegistro", targetNamespace = "http://icar.unibas.it/freesbee/", header = true)
        java.lang.String indirizzoRegistro
    ) throws SOAPFault_Exception, DAOException_Exception;
}
