package it.unibas.icar.freesbee.ws.registroservizi.client.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-12-18T14:05:48.957+01:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "WSRegistroServiziImplService", 
                  wsdlLocation = "http://localhost:8191/ws/registroServizi?wsdl",
                  targetNamespace = "http://registroservizi.ws.freesbee.icar.unibas.it/") 
public class WSRegistroServiziImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://registroservizi.ws.freesbee.icar.unibas.it/", "WSRegistroServiziImplService");
    public final static QName WSRegistroServiziImplPort = new QName("http://registroservizi.ws.freesbee.icar.unibas.it/", "WSRegistroServiziImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8191/ws/registroServizi?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSRegistroServiziImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8191/ws/registroServizi?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSRegistroServiziImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSRegistroServiziImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSRegistroServiziImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    /**
     *
     * @return
     *     returns IWSRegistroServizi
     */
    @WebEndpoint(name = "WSRegistroServiziImplPort")
    public IWSRegistroServizi getWSRegistroServiziImplPort() {
        return super.getPort(WSRegistroServiziImplPort, IWSRegistroServizi.class);
    }
}
