package it.unibas.icar.freesbee.ws.client.logger.cxf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-05-29T00:57:22.067+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "WSLoggerImplService", 
                  wsdlLocation = "http://localhost:8191/ws/logger?wsdl",
                  targetNamespace = "http://icar.unibas.it/freesbee/") 
public class WSLoggerImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://icar.unibas.it/freesbee/", "WSLoggerImplService");
    public final static QName WSLoggerImplPort = new QName("http://icar.unibas.it/freesbee/", "WSLoggerImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8191/ws/logger?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSLoggerImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8191/ws/logger?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSLoggerImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSLoggerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSLoggerImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     *
     * @return
     *     returns IWSLogger
     */
    @WebEndpoint(name = "WSLoggerImplPort")
    public IWSLogger getWSLoggerImplPort() {
        return super.getPort(WSLoggerImplPort, IWSLogger.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWSLogger
     */
    @WebEndpoint(name = "WSLoggerImplPort")
    public IWSLogger getWSLoggerImplPort(WebServiceFeature... features) {
        return super.getPort(WSLoggerImplPort, IWSLogger.class, features);
    }

}
