package it.unibas.icar.freesbee.ws.client.azione.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-06-22T17:22:43.485+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://icar.unibas.it/freesbee/", name = "IWSAzione")
@XmlSeeAlso({ObjectFactory.class})
public interface IWSAzione {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getListaAzioni", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.azione.cxf.GetListaAzioni")
    @WebMethod
    @ResponseWrapper(localName = "getListaAzioniResponse", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.azione.cxf.GetListaAzioniResponse")
    public java.util.List<it.unibas.icar.freesbee.ws.client.azione.cxf.Azione> getListaAzioni() throws SOAPFault_Exception;

    @RequestWrapper(localName = "removeAzione", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.azione.cxf.RemoveAzione")
    @WebMethod
    @ResponseWrapper(localName = "removeAzioneResponse", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.azione.cxf.RemoveAzioneResponse")
    public void removeAzione(
        @WebParam(name = "azione", targetNamespace = "")
        long azione
    ) throws SOAPFault_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAzione", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.azione.cxf.GetAzione")
    @WebMethod
    @ResponseWrapper(localName = "getAzioneResponse", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.azione.cxf.GetAzioneResponse")
    public it.unibas.icar.freesbee.ws.client.azione.cxf.Azione getAzione(
        @WebParam(name = "azione", targetNamespace = "")
        long azione
    ) throws SOAPFault_Exception;

    @RequestWrapper(localName = "addAzione", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.azione.cxf.AddAzione")
    @WebMethod
    @ResponseWrapper(localName = "addAzioneResponse", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.azione.cxf.AddAzioneResponse")
    public void addAzione(
        @WebParam(name = "azione", targetNamespace = "")
        it.unibas.icar.freesbee.ws.client.azione.cxf.Azione azione
    ) throws SOAPFault_Exception;
}
