
package it.unibas.icar.interfreesbee.nica.registroservizi.stub;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Mon Apr 07 12:55:06 CEST 2008
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebFault(name = "fault1", targetNamespace = "http://ws.registry.openspcoop.org")

public class WSRegistryNotFound_Exception extends Exception {
    public static final long serialVersionUID = 20080407125506L;
    
    private it.unibas.icar.interfreesbee.nica.registroservizi.stub.WSRegistryNotFound fault1;

    public WSRegistryNotFound_Exception() {
        super();
    }
    
    public WSRegistryNotFound_Exception(String message) {
        super(message);
    }
    
    public WSRegistryNotFound_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public WSRegistryNotFound_Exception(String message, it.unibas.icar.interfreesbee.nica.registroservizi.stub.WSRegistryNotFound fault1) {
        super(message);
        this.fault1 = fault1;
    }

    public WSRegistryNotFound_Exception(String message, it.unibas.icar.interfreesbee.nica.registroservizi.stub.WSRegistryNotFound fault1, Throwable cause) {
        super(message, cause);
        this.fault1 = fault1;
    }

    public it.unibas.icar.interfreesbee.nica.registroservizi.stub.WSRegistryNotFound getFaultInfo() {
        return this.fault1;
    }
}
