
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.ws.comune;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-06-15T17:27:07.835+02:00
 * Generated source version: 2.7.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "ComuneWS",
                      portName = "ComuneWSPort",
                      targetNamespace = "http://comune.ws.com/",
//                      wsdlLocation = "http://localhost:8080/comuneWSApplication/ComuneWS?wsdl",
                      wsdlLocation = "http://sp.example.unibas:8080/comuneWSApplication/ComuneWS?wsdl",
                      endpointInterface = "com.ws.comune.ComuneWS")
                      
public class ComuneWSImpl implements ComuneWS {

    private static final Logger LOG = Logger.getLogger(ComuneWSImpl.class.getName());

    /* (non-Javadoc)
     * @see com.ws.comune.ComuneWS#cercaCittadino(java.lang.String  codiceFiscale )*
     */
    public com.ws.comune.Cittadino cercaCittadino(java.lang.String codiceFiscale) { 
        LOG.info("Executing operation cercaCittadino");
        System.out.println(codiceFiscale);
        try {
            com.ws.comune.Cittadino _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
