
package it.unibas.silvio.ws.istanza.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Wed Jun 04 11:50:21 CEST 2008
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebService(targetNamespace = "http://freesbee.unibas.it", name = "IWSIstanza")

public interface IWSIstanza {

    @RequestWrapper(localName = "avviaIstanza", targetNamespace = "http://freesbee.unibas.it", className = "it.unibas.silvio.ws.istanza.client.AvviaIstanza")
    @ResponseWrapper(localName = "avviaIstanzaResponse", targetNamespace = "http://freesbee.unibas.it", className = "it.unibas.silvio.ws.istanza.client.AvviaIstanzaResponse")
    @WebMethod
    public void avviaIstanza(
        @WebParam(name = "id_istanza", targetNamespace = "")
        long idIstanza
    );
}
