
package it.unibas.silvio.ws.istanza.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import it.unibas.silvio.ws.istanza.client.IWSIstanza;

/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Wed Jun 04 11:50:21 CEST 2008
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebServiceClient(name = "WSIstanzaImplService", targetNamespace = "http://istanza.ws.silvio.unibas.it/", wsdlLocation = "http://localhost:9191/ws/istanza?wsdl")
public class WSIstanzaImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://istanza.ws.silvio.unibas.it/", "WSIstanzaImplService");
    public final static QName WSIstanzaImplPort = new QName("http://istanza.ws.silvio.unibas.it/", "WSIstanzaImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9191/ws/istanza?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:9191/ws/istanza?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public WSIstanzaImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSIstanzaImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSIstanzaImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns WSIstanzaImplPort
     */
    @WebEndpoint(name = "WSIstanzaImplPort")
    public IWSIstanza getWSIstanzaImplPort() {
        return (IWSIstanza)super.getPort(WSIstanzaImplPort, IWSIstanza.class);
    }

}
