package it.unibas.icar.freesbee.ws.client.servizio.cxf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2014-04-30T11:43:23.017+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "WSServizioImplService", 
                  wsdlLocation = "http://localhost:8191/ws/servizio?wsdl",
                  targetNamespace = "http://web.ws.freesbee.icar.unibas.it/") 
public class WSServizioImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://web.ws.freesbee.icar.unibas.it/", "WSServizioImplService");
    public final static QName WSServizioImplPort = new QName("http://web.ws.freesbee.icar.unibas.it/", "WSServizioImplPort");
    
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8191/ws/servizio?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSServizioImplService.class.getName()).log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8191/ws/servizio?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSServizioImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSServizioImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSServizioImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSServizioImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSServizioImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSServizioImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns IWSServizio
     */
    @WebEndpoint(name = "WSServizioImplPort")
    public IWSServizio getWSServizioImplPort() {
        return super.getPort(WSServizioImplPort, IWSServizio.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWSServizio
     */
    @WebEndpoint(name = "WSServizioImplPort")
    public IWSServizio getWSServizioImplPort(WebServiceFeature... features) {
        return super.getPort(WSServizioImplPort, IWSServizio.class, features);
    }

}
