package com.ws.comune;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-06-15T17:27:07.857+02:00
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://comune.ws.com/", name = "ComuneWS")
@XmlSeeAlso({ObjectFactory.class})
public interface ComuneWS {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://comune.ws.com/ComuneWS/cercaCittadinoRequest", output = "http://comune.ws.com/ComuneWS/cercaCittadinoResponse")
    @RequestWrapper(localName = "cercaCittadino", targetNamespace = "http://comune.ws.com/", className = "com.ws.comune.CercaCittadino")
    @WebMethod
    @ResponseWrapper(localName = "cercaCittadinoResponse", targetNamespace = "http://comune.ws.com/", className = "com.ws.comune.CercaCittadinoResponse")
    public com.ws.comune.Cittadino cercaCittadino(
        @WebParam(name = "codiceFiscale", targetNamespace = "")
        java.lang.String codiceFiscale
    );
}
