<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2008

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://ws.ap6.progettoicar.it/" exclude-result-prefixes="xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/datiCompleti">
		<getTitolari>
			<xsl:attribute name="xsi:schemaLocation">
				<xsl:value-of select="'http://ws.ap6.progettoicar.it/ C:/DOCUME~1/LAGUAR~1/Desktop/target.xsd'"/>
			</xsl:attribute>
			<titolariXML xmlns="">
				<xsl:template match="datiCostanti">
					<xsl:template match="data_rilevazione">
						<xsl:attribute name="data_rilevazione">
							<xsl:value-of select="/datiCompleti/datiCostanti/data_rilevazione"/>
						</xsl:attribute>
					</xsl:template>
				</xsl:template>
				<xsl:template select="datiCostanti">
					<xsl:template select="codistatregione">
						<xsl:attribute name="codistatregione">
							<xsl:value-of select="/datiCompleti/datiCostanti/codistatregione"/>
						</xsl:attribute>
					</xsl:template>
				</xsl:template>
				<titolaritype>
					<xsl:for-each select="datiDB">
					<titolareitem>
							<iva_cf>
							   <xsl:value-of select="/datiCompleti/datiDB/titolare.iva_cf"/>
							</iva_cf>
							<denominazione>
								<xsl:value-of select="/datiCompleti/datiDB/titolare.denominazione"/>
							</denominazione>
					  <indirizzo>
							<via>
							  <xsl:value-of select="/datiCompleti/datiDB/titolare.via"/>
							</via>
							<codistat_pvcomune>
								<xsl:value-of select="/datiCompleti/datiDB/titolare.codistat_pvcomune"/>
							</codistat_pvcomune>
							<cap>
								<xsl:value-of select="/datiCompleti/datiDB/titolare.cap"/>
							</cap>
					   </indirizzo>
					</titolareitem>
					</xsl:for-each>
				</titolaritype>
			</titolariXML>
		</getTitolari>
	</xsl:template>
	<xsl:template match="/datiCompleti/datiCostanti/data_rilevazione">	
           <xsl:value-of select="text()"/> 
    </xsl:template>
    <xsl:template match="/datiCompleti/datiCostanti/codistatregione">	
           <xsl:value-of select="text()"/> 
    </xsl:template>	
	<!--xsl:template match="/datiCompleti/datiDB/titolare.iva_cf">	
           <xsl:value-of select="text()"/> 
    </xsl:template>	
	<xsl:template match="/datiCompleti/datiDB/titolare.denominazione">	
           <xsl:value-of select="text()"/> 
    </xsl:template>	
	<xsl:template match="/datiCompleti/datiDB/titolare.via">	
           <xsl:value-of select="text()"/> 
    </xsl:template>	<xsl:template match="/datiCompleti/datiDB/titolare.codistat_pvcomune">	
           <xsl:value-of select="text()"/> 
    </xsl:template>	<xsl:template match="/datiCompleti/datiDB/titolare.cap">	
           <xsl:value-of select="text()"/> 
    </xsl:template-->	
</xsl:stylesheet>
