package it.unibas.icar.freesbee.test.messaggi.attachment.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2015-01-19T22:10:10.613+01:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://icar.unibas.it/freesbee/", name = "IWSVerificaInstallazione")
@XmlSeeAlso({ObjectFactory.class})
public interface IWSVerificaInstallazione {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "testAttachmentEcho", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.test.messaggi.attachment.client.TestAttachmentEcho")
    @WebMethod
    @ResponseWrapper(localName = "testAttachmentEchoResponse", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.test.messaggi.attachment.client.TestAttachmentEchoResponse")
    public byte[] testAttachmentEcho(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0
    ) throws SOAPFault_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "verificaInstallazione", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.test.messaggi.attachment.client.VerificaInstallazione")
    @WebMethod
    @ResponseWrapper(localName = "verificaInstallazioneResponse", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.test.messaggi.attachment.client.VerificaInstallazioneResponse")
    public java.lang.String verificaInstallazione() throws SOAPFault_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "testAttachmentEchoMessage", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.test.messaggi.attachment.client.TestAttachmentEchoMessage")
    @WebMethod
    @ResponseWrapper(localName = "testAttachmentEchoMessageResponse", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.test.messaggi.attachment.client.TestAttachmentEchoMessageResponse")
    public it.unibas.icar.freesbee.test.messaggi.attachment.client.MessaggioInstallazione testAttachmentEchoMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    ) throws SOAPFault_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "testAttachment", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.test.messaggi.attachment.client.TestAttachment")
    @WebMethod
    @ResponseWrapper(localName = "testAttachmentResponse", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.test.messaggi.attachment.client.TestAttachmentResponse")
    public byte[] testAttachment(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0
    ) throws SOAPFault_Exception;
}
