
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package it.unibas.icar.freesbee.test.messaggi.attachment.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2015-01-19T22:10:10.596+01:00
 * Generated source version: 2.5.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "WSVerificaInstallazioneImplService",
                      portName = "WSVerificaInstallazioneImplPort",
                      targetNamespace = "http://icar.unibas.it/freesbee/",
                      wsdlLocation = "http://localhost:8191/ws/verificaInstallazione?wsdl",
                      endpointInterface = "it.unibas.icar.freesbee.test.messaggi.attachment.client.IWSVerificaInstallazione")
                      
public class IWSVerificaInstallazioneImpl implements IWSVerificaInstallazione {

    private static final Logger LOG = Logger.getLogger(IWSVerificaInstallazioneImpl.class.getName());

    /* (non-Javadoc)
     * @see it.unibas.icar.freesbee.test.messaggi.attachment.client.IWSVerificaInstallazione#testAttachmentEcho(byte[]  arg0 )*
     */
    public byte[] testAttachmentEcho(byte[] arg0) throws SOAPFault_Exception    { 
        LOG.info("Executing operation testAttachmentEcho");
        System.out.println(arg0);
        try {
            byte[] _return = new byte[0];
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SOAPFault_Exception("SOAPFault...");
    }

    /* (non-Javadoc)
     * @see it.unibas.icar.freesbee.test.messaggi.attachment.client.IWSVerificaInstallazione#verificaInstallazione(*
     */
    public java.lang.String verificaInstallazione() throws SOAPFault_Exception    { 
        LOG.info("Executing operation verificaInstallazione");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SOAPFault_Exception("SOAPFault...");
    }

    /* (non-Javadoc)
     * @see it.unibas.icar.freesbee.test.messaggi.attachment.client.IWSVerificaInstallazione#testAttachmentEchoMessage(byte[]  arg0 ,)java.lang.String  arg1 )*
     */
    public it.unibas.icar.freesbee.test.messaggi.attachment.client.MessaggioInstallazione testAttachmentEchoMessage(byte[] arg0,java.lang.String arg1) throws SOAPFault_Exception    { 
        LOG.info("Executing operation testAttachmentEchoMessage");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            it.unibas.icar.freesbee.test.messaggi.attachment.client.MessaggioInstallazione _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SOAPFault_Exception("SOAPFault...");
    }

    /* (non-Javadoc)
     * @see it.unibas.icar.freesbee.test.messaggi.attachment.client.IWSVerificaInstallazione#testAttachment(byte[]  arg0 )*
     */
    public byte[] testAttachment(byte[] arg0) throws SOAPFault_Exception    { 
        LOG.info("Executing operation testAttachment");
        System.out.println(arg0);
        try {
            byte[] _return = new byte[0];
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SOAPFault_Exception("SOAPFault...");
    }

}
