package it.unibas.icar.freesbee.test.messaggi.attachment.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2 2015-01-19T22:10:10.619+01:00
 * Generated source version: 2.5.2
 *
 */
@WebServiceClient(name = "WSVerificaInstallazioneImplService",
        wsdlLocation = "http://localhost:8191/ws/verificaInstallazione?wsdl",
        targetNamespace = "http://icar.unibas.it/freesbee/")
public class WSVerificaInstallazioneImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://icar.unibas.it/freesbee/", "WSVerificaInstallazioneImplService");
    public final static QName WSVerificaInstallazioneImplPort = new QName("http://icar.unibas.it/freesbee/", "WSVerificaInstallazioneImplPort");

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8191/ws/verificaInstallazione?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSVerificaInstallazioneImplService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "http://localhost:8191/ws/verificaInstallazione?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSVerificaInstallazioneImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSVerificaInstallazioneImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSVerificaInstallazioneImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSVerificaInstallazioneImplService(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSVerificaInstallazioneImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSVerificaInstallazioneImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return returns IWSVerificaInstallazione
     */
    @WebEndpoint(name = "WSVerificaInstallazioneImplPort")
    public IWSVerificaInstallazione getWSVerificaInstallazioneImplPort() {
        return super.getPort(WSVerificaInstallazioneImplPort, IWSVerificaInstallazione.class);
    }

    /**
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to
     * configure on the proxy. Supported features not in the
     * <code>features</code> parameter will have their default values.
     * @return returns IWSVerificaInstallazione
     */
    @WebEndpoint(name = "WSVerificaInstallazioneImplPort")
    public IWSVerificaInstallazione getWSVerificaInstallazioneImplPort(WebServiceFeature... features) {
        return super.getPort(WSVerificaInstallazioneImplPort, IWSVerificaInstallazione.class, features);
    }

}
