
package com.ws.aci;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-06-15T00:35:58.006+02:00
 * Generated source version: 2.7.4
 * 
 */
public final class AciWS_AciWSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://aci.ws.com/", "AciWS");

    private AciWS_AciWSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AciWS_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AciWS_Service ss = new AciWS_Service(wsdlURL, SERVICE_NAME);
        AciWS port = ss.getAciWSPort();  
        
        {
        System.out.println("Invoking cercaImmatricolazione...");
        java.lang.String _cercaImmatricolazione_targa = "";
        com.ws.aci.Immatricolazione _cercaImmatricolazione__return = port.cercaImmatricolazione(_cercaImmatricolazione_targa);
        System.out.println("cercaImmatricolazione.result=" + _cercaImmatricolazione__return);


        }

        System.exit(0);
    }

}
