package it.unibas.icar.freesbee.ws.client.portadelegata.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-06-22T17:32:15.437+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://icar.unibas.it/freesbee/", name = "IWSPortaDelegata")
@XmlSeeAlso({ObjectFactory.class})
public interface IWSPortaDelegata {

    @RequestWrapper(localName = "removePortaDelegata", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.portadelegata.cxf.RemovePortaDelegata")
    @WebMethod
    @ResponseWrapper(localName = "removePortaDelegataResponse", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.portadelegata.cxf.RemovePortaDelegataResponse")
    public void removePortaDelegata(
        @WebParam(name = "portaDelegata", targetNamespace = "")
        long portaDelegata
    ) throws SOAPFault_Exception;

    @RequestWrapper(localName = "addPortaDelegata", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.portadelegata.cxf.AddPortaDelegata")
    @WebMethod
    @ResponseWrapper(localName = "addPortaDelegataResponse", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.portadelegata.cxf.AddPortaDelegataResponse")
    public void addPortaDelegata(
        @WebParam(name = "portaDelegata", targetNamespace = "")
        it.unibas.icar.freesbee.ws.client.portadelegata.cxf.PortaDelegata portaDelegata
    ) throws SOAPFault_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getListaPorteDelegate", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.portadelegata.cxf.GetListaPorteDelegate")
    @WebMethod
    @ResponseWrapper(localName = "getListaPorteDelegateResponse", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.portadelegata.cxf.GetListaPorteDelegateResponse")
    public java.util.List<it.unibas.icar.freesbee.ws.client.portadelegata.cxf.PortaDelegata> getListaPorteDelegate() throws SOAPFault_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPortaDelegata", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.portadelegata.cxf.GetPortaDelegata")
    @WebMethod
    @ResponseWrapper(localName = "getPortaDelegataResponse", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.portadelegata.cxf.GetPortaDelegataResponse")
    public it.unibas.icar.freesbee.ws.client.portadelegata.cxf.PortaDelegata getPortaDelegata(
        @WebParam(name = "portaDelegata", targetNamespace = "")
        long portaDelegata
    ) throws SOAPFault_Exception;
}
