package it.unibas.icar.freesbee.ws.client.portadelegata.cxf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-06-22T17:32:15.449+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "WSPortaDelegataImplService", 
                  wsdlLocation = "http://localhost:8191/ws/portaDelegata?wsdl",
                  targetNamespace = "http://web.ws.freesbee.icar.unibas.it/") 
public class WSPortaDelegataImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://web.ws.freesbee.icar.unibas.it/", "WSPortaDelegataImplService");
    public final static QName WSPortaDelegataImplPort = new QName("http://web.ws.freesbee.icar.unibas.it/", "WSPortaDelegataImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8191/ws/portaDelegata?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WSPortaDelegataImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8191/ws/portaDelegata?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WSPortaDelegataImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSPortaDelegataImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSPortaDelegataImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSPortaDelegataImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSPortaDelegataImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WSPortaDelegataImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns IWSPortaDelegata
     */
    @WebEndpoint(name = "WSPortaDelegataImplPort")
    public IWSPortaDelegata getWSPortaDelegataImplPort() {
        return super.getPort(WSPortaDelegataImplPort, IWSPortaDelegata.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWSPortaDelegata
     */
    @WebEndpoint(name = "WSPortaDelegataImplPort")
    public IWSPortaDelegata getWSPortaDelegataImplPort(WebServiceFeature... features) {
        return super.getPort(WSPortaDelegataImplPort, IWSPortaDelegata.class, features);
    }

}
