<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2008

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://axisversion.sample" exclude-result-prefixes="xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/datiRisposta">
		<getVersionResponse>
			<xsl:attribute name="xsi:schemaLocation">
				<xsl:value-of select="'http://axisversion.sample C:/Users/Donatello/Desktop/target.xsd'"/>
			</xsl:attribute>
			<xsl:for-each select="datiCompleti">
				<xsl:for-each select="datiCostanti">
					<xsl:for-each select="Stringa">
						<return>
							<xsl:value-of select="."/>
						</return>
					</xsl:for-each>
				</xsl:for-each>
			</xsl:for-each>
		</getVersionResponse>
	</xsl:template>
</xsl:stylesheet>
