
package it.unibas.freesbee.ge.web.ws.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Tue Aug 04 16:42:32 CEST 2009
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebService(targetNamespace = "http://ge.freesbee.unibas.it/", name = "IWSAutenticazione")

public interface IWSAutenticazione {

    @RequestWrapper(localName = "cambiaPassword", targetNamespace = "http://ge.freesbee.unibas.it/", className = "it.unibas.freesbee.ge.CambiaPassword")
    @ResponseWrapper(localName = "cambiaPasswordResponse", targetNamespace = "http://ge.freesbee.unibas.it/", className = "it.unibas.freesbee.ge.CambiaPasswordResponse")
    @WebMethod
    public void cambiaPassword(
        @WebParam(name = "nuovaPassword", targetNamespace = "")
        java.lang.String nuovaPassword,
        @WebParam(name = "nomeUtente", targetNamespace = "")
        java.lang.String nomeUtente
    ) throws SOAPFaultException;

    @RequestWrapper(localName = "autentica", targetNamespace = "http://ge.freesbee.unibas.it/", className = "it.unibas.freesbee.ge.Autentica")
    @ResponseWrapper(localName = "autenticaResponse", targetNamespace = "http://ge.freesbee.unibas.it/", className = "it.unibas.freesbee.ge.AutenticaResponse")
    @WebMethod
    public void autentica(
        @WebParam(name = "nomeUtente", targetNamespace = "")
        java.lang.String nomeUtente
    ) throws SOAPFaultException;
}
