package it.unibas.freesbee.ge.web.ws.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.3
 * Tue Oct 20 23:16:34 CEST 2009
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://ge.freesbee.unibas.it/", name = "IWSCategoriaEventiInterna")
@XmlSeeAlso({ObjectFactory.class})
public interface IWSCategoriaEventiInterna {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCategoriaEventiInterna", targetNamespace = "http://ge.freesbee.unibas.it/", className = "it.unibas.freesbee.ge.GetCategoriaEventiInterna")
    @ResponseWrapper(localName = "getCategoriaEventiInternaResponse", targetNamespace = "http://ge.freesbee.unibas.it/", className = "it.unibas.freesbee.ge.GetCategoriaEventiInternaResponse")
    @WebMethod
    public CategoriaEventiInterna getCategoriaEventiInterna(
        @WebParam(name = "categoriaEventi", targetNamespace = "")
        java.lang.String categoriaEventi
    ) throws SOAPFaultException;

    @RequestWrapper(localName = "addCategoriaEventiInterna", targetNamespace = "http://ge.freesbee.unibas.it/", className = "it.unibas.freesbee.ge.AddCategoriaEventiInterna")
    @ResponseWrapper(localName = "addCategoriaEventiInternaResponse", targetNamespace = "http://ge.freesbee.unibas.it/", className = "it.unibas.freesbee.ge.AddCategoriaEventiInternaResponse")
    @WebMethod
    public void addCategoriaEventiInterna(
        @WebParam(name = "categoriaEventi", targetNamespace = "")
        CategoriaEventiInterna categoriaEventi
    ) throws SOAPFaultException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getListaCategoriaEventiInterne", targetNamespace = "http://ge.freesbee.unibas.it/", className = "it.unibas.freesbee.ge.GetListaCategoriaEventiInterne")
    @ResponseWrapper(localName = "getListaCategoriaEventiInterneResponse", targetNamespace = "http://ge.freesbee.unibas.it/", className = "it.unibas.freesbee.ge.GetListaCategoriaEventiInterneResponse")
    @WebMethod
    public java.util.List<CategoriaEventiInterna> getListaCategoriaEventiInterne() throws SOAPFaultException;

    @RequestWrapper(localName = "updateCategoriaEventiInterna", targetNamespace = "http://ge.freesbee.unibas.it/", className = "it.unibas.freesbee.ge.UpdateCategoriaEventiInterna")
    @ResponseWrapper(localName = "updateCategoriaEventiInternaResponse", targetNamespace = "http://ge.freesbee.unibas.it/", className = "it.unibas.freesbee.ge.UpdateCategoriaEventiInternaResponse")
    @WebMethod
    public void updateCategoriaEventiInterna(
        @WebParam(name = "categoriaEventi", targetNamespace = "")
        CategoriaEventiInterna categoriaEventi
    ) throws SOAPFaultException;
}
