package it.unibas.freesbee.ge.web.ws.stub;

import javax.jws.WebMethod;

import javax.jws.WebParam;

import javax.jws.WebResult;

import javax.jws.WebService;

import javax.xml.ws.RequestWrapper;



import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Mon Aug 03 19:25:25 CEST 2009
 * Generated source version: 2.0.4-incubator
 * 
 */
@WebService(targetNamespace = "http://ge.freesbee.unibas.it/", name = "IWSConfigura")
public interface IWSConfigura {

    @RequestWrapper(localName = "modificaConfigurazioneSP", targetNamespace = "http://ge.freesbee.unibas.it/", className = "it.unibas.freesbee.ge.ModificaConfigurazioneSP")
    @ResponseWrapper(localName = "modificaConfigurazioneSPResponse", targetNamespace = "http://ge.freesbee.unibas.it/", className = "it.unibas.freesbee.ge.ModificaConfigurazioneSPResponse")
    @WebMethod
    public void modificaConfigurazioneSP(
            @WebParam(name = "datiConfigurazione", targetNamespace = "") DatiConfigurazione datiConfigurazione) throws SOAPFaultException;

    @RequestWrapper(localName = "modificaConfigurazioneGE", targetNamespace = "http://ge.freesbee.unibas.it/", className = "it.unibas.freesbee.ge.ModificaConfigurazioneGE")
    @ResponseWrapper(localName = "modificaConfigurazioneGEResponse", targetNamespace = "http://ge.freesbee.unibas.it/", className = "it.unibas.freesbee.ge.ModificaConfigurazioneGEResponse")
    @WebMethod
    public void modificaConfigurazioneGE(
            @WebParam(name = "datiConfigurazione", targetNamespace = "") DatiConfigurazione datiConfigurazione) throws SOAPFaultException;

    @WebResult(name = "datiConfigurazione", targetNamespace = "")
    @RequestWrapper(localName = "caricaConfigurazione", targetNamespace = "http://ge.freesbee.unibas.it/", className = "it.unibas.freesbee.ge.CaricaConfigurazione")
    @ResponseWrapper(localName = "caricaConfigurazioneResponse", targetNamespace = "http://ge.freesbee.unibas.it/", className = "it.unibas.freesbee.ge.CaricaConfigurazioneResponse")
    @WebMethod
    public DatiConfigurazione caricaConfigurazione() throws SOAPFaultException;
}
