package it.unibas.freesbee.ge.web.ws.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.3
 * Tue Oct 20 23:24:48 CEST 2009
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://ge.freesbee.unibas.it/", name = "IWSCategoriaEventiEsterna")
@XmlSeeAlso({ObjectFactory.class})
public interface IWSCategoriaEventiEsterna {

    @RequestWrapper(localName = "updateCategoriaEventiEsterna", targetNamespace = "http://ge.freesbee.unibas.it/", className = "it.unibas.freesbee.ge.UpdateCategoriaEventiEsterna")
    @ResponseWrapper(localName = "updateCategoriaEventiEsternaResponse", targetNamespace = "http://ge.freesbee.unibas.it/", className = "it.unibas.freesbee.ge.UpdateCategoriaEventiEsternaResponse")
    @WebMethod
    public void updateCategoriaEventiEsterna(
        @WebParam(name = "categoriaEventi", targetNamespace = "")
        CategoriaEventiEsterna categoriaEventi
    ) throws SOAPFaultException;

    @RequestWrapper(localName = "addCategoriaEventiEsterna", targetNamespace = "http://ge.freesbee.unibas.it/", className = "it.unibas.freesbee.ge.AddCategoriaEventiEsterna")
    @ResponseWrapper(localName = "addCategoriaEventiEsternaResponse", targetNamespace = "http://ge.freesbee.unibas.it/", className = "it.unibas.freesbee.ge.AddCategoriaEventiEsternaResponse")
    @WebMethod
    public void addCategoriaEventiEsterna(
        @WebParam(name = "categoriaEventi", targetNamespace = "")
        CategoriaEventiEsterna categoriaEventi
    ) throws SOAPFaultException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCategoriaEventiEsterna", targetNamespace = "http://ge.freesbee.unibas.it/", className = "it.unibas.freesbee.ge.GetCategoriaEventiEsterna")
    @ResponseWrapper(localName = "getCategoriaEventiEsternaResponse", targetNamespace = "http://ge.freesbee.unibas.it/", className = "it.unibas.freesbee.ge.GetCategoriaEventiEsternaResponse")
    @WebMethod
    public CategoriaEventiEsterna getCategoriaEventiEsterna(
        @WebParam(name = "categoriaEventi", targetNamespace = "")
        java.lang.String categoriaEventi
    ) throws SOAPFaultException;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getListaCategoriaEventiEsterne", targetNamespace = "http://ge.freesbee.unibas.it/", className = "it.unibas.freesbee.ge.GetListaCategoriaEventiEsterne")
    @ResponseWrapper(localName = "getListaCategoriaEventiEsterneResponse", targetNamespace = "http://ge.freesbee.unibas.it/", className = "it.unibas.freesbee.ge.GetListaCategoriaEventiEsterneResponse")
    @WebMethod
    public java.util.List<CategoriaEventiEsterna> getListaCategoriaEventiEsterne() throws SOAPFaultException;
}
