
package it.unibas.freesbee.ge.web.ws.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Tue Aug 04 16:42:32 CEST 2009
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebServiceClient(name = "WSAutenticazioneImplService", targetNamespace = "http://ge.freesbee.unibas.it/", wsdlLocation = "file:autenticazione.wsdl")
public class WSAutenticazioneImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ge.freesbee.unibas.it/", "WSAutenticazioneImplService");
    public final static QName WSAutenticazioneImplPort = new QName("http://ge.freesbee.unibas.it/", "WSAutenticazioneImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:autenticazione.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:autenticazione.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public WSAutenticazioneImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSAutenticazioneImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSAutenticazioneImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns WSAutenticazioneImplPort
     */
    @WebEndpoint(name = "WSAutenticazioneImplPort")
    public IWSAutenticazione getWSAutenticazioneImplPort() {
        return (IWSAutenticazione)super.getPort(WSAutenticazioneImplPort, IWSAutenticazione.class);
    }

}
