
package it.unibas.freesbee.ge.web.ws.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by Apache CXF (incubator) 2.0.4-incubator
 * Tue Aug 04 11:32:34 CEST 2009
 * Generated source version: 2.0.4-incubator
 * 
 */

@WebServiceClient(name = "WSGestioneGestoreEventiImplService", targetNamespace = "http://ge.freesbee.unibas.it/", wsdlLocation = "file:gestioneGestoreEventi.wsdl")
public class WSGestioneGestoreEventiImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://ge.freesbee.unibas.it/", "WSGestioneGestoreEventiImplService");
    public final static QName WSGestioneGestoreEventiImplPort = new QName("http://ge.freesbee.unibas.it/", "WSGestioneGestoreEventiImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:gestioneGestoreEventi.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:gestioneGestoreEventi.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public WSGestioneGestoreEventiImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSGestioneGestoreEventiImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSGestioneGestoreEventiImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns WSGestioneGestoreEventiImplPort
     */
    @WebEndpoint(name = "WSGestioneGestoreEventiImplPort")
    public IWSGestioneGestoreEventi getWSGestioneGestoreEventiImplPort() {
        return (IWSGestioneGestoreEventi)super.getPort(WSGestioneGestoreEventiImplPort, IWSGestioneGestoreEventi.class);
    }

}
