
package it.unibas.icar.freesbee.ws.registroservizi.client.stub;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-12-13T16:50:24.921+01:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "DAOException", targetNamespace = "http://icar.unibas.it/freesbee/")
public class DAOException_Exception extends Exception {
    
    private it.unibas.icar.freesbee.ws.registroservizi.client.stub.DAOException daoException;

    public DAOException_Exception() {
        super();
    }
    
    public DAOException_Exception(String message) {
        super(message);
    }
    
    public DAOException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public DAOException_Exception(String message, it.unibas.icar.freesbee.ws.registroservizi.client.stub.DAOException daoException) {
        super(message);
        this.daoException = daoException;
    }

    public DAOException_Exception(String message, it.unibas.icar.freesbee.ws.registroservizi.client.stub.DAOException daoException, Throwable cause) {
        super(message, cause);
        this.daoException = daoException;
    }

    public it.unibas.icar.freesbee.ws.registroservizi.client.stub.DAOException getFaultInfo() {
        return this.daoException;
    }
}
