
package it.unibas.icar.freesbee.ws.registroservizi.client.stub;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-12-13T16:50:24.913+01:00
 * Generated source version: 2.7.7
 */

@WebFault(name = "SOAPFault", targetNamespace = "http://icar.unibas.it/freesbee/")
public class SOAPFault_Exception extends Exception {
    
    private it.unibas.icar.freesbee.ws.registroservizi.client.stub.SOAPFault soapFault;

    public SOAPFault_Exception() {
        super();
    }
    
    public SOAPFault_Exception(String message) {
        super(message);
    }
    
    public SOAPFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public SOAPFault_Exception(String message, it.unibas.icar.freesbee.ws.registroservizi.client.stub.SOAPFault soapFault) {
        super(message);
        this.soapFault = soapFault;
    }

    public SOAPFault_Exception(String message, it.unibas.icar.freesbee.ws.registroservizi.client.stub.SOAPFault soapFault, Throwable cause) {
        super(message, cause);
        this.soapFault = soapFault;
    }

    public it.unibas.icar.freesbee.ws.registroservizi.client.stub.SOAPFault getFaultInfo() {
        return this.soapFault;
    }
}
