package it.unibas.icar.freesbee.ws.registroservizi.client.stub;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2013-12-13T16:50:24.974+01:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "WSRegistroServiziImplService", 
                  wsdlLocation = "/Users/michele/Desktop/gestioneGareServerICARLAB/registroServizi_3.wsdl",
                  targetNamespace = "http://registroservizi.ws.freesbee.icar.unibas.it/") 
public class WSRegistroServiziImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://registroservizi.ws.freesbee.icar.unibas.it/", "WSRegistroServiziImplService");
    public final static QName WSRegistroServiziImplPort = new QName("http://registroservizi.ws.freesbee.icar.unibas.it/", "WSRegistroServiziImplPort");
    static {
        URL url = WSRegistroServiziImplService.class.getResource("/Users/michele/Desktop/gestioneGareServerICARLAB/registroServizi_3.wsdl");
        if (url == null) {
            url = WSRegistroServiziImplService.class.getClassLoader().getResource("/Users/michele/Desktop/gestioneGareServerICARLAB/registroServizi_3.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(WSRegistroServiziImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/Users/michele/Desktop/gestioneGareServerICARLAB/registroServizi_3.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public WSRegistroServiziImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WSRegistroServiziImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSRegistroServiziImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     *
     * @return
     *     returns IWSRegistroServizi
     */
    @WebEndpoint(name = "WSRegistroServiziImplPort")
    public IWSRegistroServizi getWSRegistroServiziImplPort() {
        return super.getPort(WSRegistroServiziImplPort, IWSRegistroServizi.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWSRegistroServizi
     */
    @WebEndpoint(name = "WSRegistroServiziImplPort")
    public IWSRegistroServizi getWSRegistroServiziImplPort(WebServiceFeature... features) {
        return super.getPort(WSRegistroServiziImplPort, IWSRegistroServizi.class, features);
    }

}
