
package com.ws.aci;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-06-15T00:35:58.069+02:00
 * Generated source version: 2.7.4
 * 
 */
 
public class AciWS_AciWSPort_Server{

    protected AciWS_AciWSPort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new AciWSImpl();
//        String address = "http://localhost:8080/aciWebService/AciWS";
        String address = "http://sp.example.unibas:8080/aciWebService/AciWS";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new AciWS_AciWSPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
