package it.unibas.freesbeesla.tracciatura.modello.base;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;

import it.unibas.freesbeesla.tracciatura.modello.*;

import it.unibas.freesbeesla.tracciatura.modello.dao.*;

            

/**
 * This class was autogenerated by Torque on:
 *
 * [Tue Dec 14 20:27:47 CET 2010]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to ConfigurazioneSP
 */
public abstract class BaseConfigurazioneSP extends BaseObject
{
    /** The Peer class */
    private static final ConfigurazioneSPPeer peer =
        new ConfigurazioneSPPeer();

        
    /** The value for the id field */
    private Long id;
      
    /** The value for the urlFreesbeeSp field */
    private String urlFreesbeeSp;
      
    /** The value for the risorsa field */
    private String risorsa;
      
    /** The value for the autenticazione field */
    private String autenticazione;
      
    /** The value for the risorsaPdMonitoraggioSla field */
    private String risorsaPdMonitoraggioSla;
      
    /** The value for the risorsaPdMonitoraggioStato field */
    private String risorsaPdMonitoraggioStato;
  
            
    /**
     * Get the Id
     *
     * @return Long
     */
    public Long getId()
    {
        return id;
    }

                        
    /**
     * Set the value of Id
     *
     * @param v new value
     */
    public void setId(Long v) 
    {
    
                  if (!ObjectUtils.equals(this.id, v))
              {
            this.id = v;
            setModified(true);
        }
    
          
              }
          
    /**
     * Get the UrlFreesbeeSp
     *
     * @return String
     */
    public String getUrlFreesbeeSp()
    {
        return urlFreesbeeSp;
    }

                        
    /**
     * Set the value of UrlFreesbeeSp
     *
     * @param v new value
     */
    public void setUrlFreesbeeSp(String v) 
    {
    
                  if (!ObjectUtils.equals(this.urlFreesbeeSp, v))
              {
            this.urlFreesbeeSp = v;
            setModified(true);
        }
    
          
              }
          
    /**
     * Get the Risorsa
     *
     * @return String
     */
    public String getRisorsa()
    {
        return risorsa;
    }

                        
    /**
     * Set the value of Risorsa
     *
     * @param v new value
     */
    public void setRisorsa(String v) 
    {
    
                  if (!ObjectUtils.equals(this.risorsa, v))
              {
            this.risorsa = v;
            setModified(true);
        }
    
          
              }
          
    /**
     * Get the Autenticazione
     *
     * @return String
     */
    public String getAutenticazione()
    {
        return autenticazione;
    }

                        
    /**
     * Set the value of Autenticazione
     *
     * @param v new value
     */
    public void setAutenticazione(String v) 
    {
    
                  if (!ObjectUtils.equals(this.autenticazione, v))
              {
            this.autenticazione = v;
            setModified(true);
        }
    
          
              }
          
    /**
     * Get the RisorsaPdMonitoraggioSla
     *
     * @return String
     */
    public String getRisorsaPdMonitoraggioSla()
    {
        return risorsaPdMonitoraggioSla;
    }

                        
    /**
     * Set the value of RisorsaPdMonitoraggioSla
     *
     * @param v new value
     */
    public void setRisorsaPdMonitoraggioSla(String v) 
    {
    
                  if (!ObjectUtils.equals(this.risorsaPdMonitoraggioSla, v))
              {
            this.risorsaPdMonitoraggioSla = v;
            setModified(true);
        }
    
          
              }
          
    /**
     * Get the RisorsaPdMonitoraggioStato
     *
     * @return String
     */
    public String getRisorsaPdMonitoraggioStato()
    {
        return risorsaPdMonitoraggioStato;
    }

                        
    /**
     * Set the value of RisorsaPdMonitoraggioStato
     *
     * @param v new value
     */
    public void setRisorsaPdMonitoraggioStato(String v) 
    {
    
                  if (!ObjectUtils.equals(this.risorsaPdMonitoraggioStato, v))
              {
            this.risorsaPdMonitoraggioStato = v;
            setModified(true);
        }
    
          
              }
  
         
                
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList();
              fieldNames.add("Id");
              fieldNames.add("UrlFreesbeeSp");
              fieldNames.add("Risorsa");
              fieldNames.add("Autenticazione");
              fieldNames.add("RisorsaPdMonitoraggioSla");
              fieldNames.add("RisorsaPdMonitoraggioStato");
              fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
          if (name.equals("Id"))
        {
                return getId();
            }
          if (name.equals("UrlFreesbeeSp"))
        {
                return getUrlFreesbeeSp();
            }
          if (name.equals("Risorsa"))
        {
                return getRisorsa();
            }
          if (name.equals("Autenticazione"))
        {
                return getAutenticazione();
            }
          if (name.equals("RisorsaPdMonitoraggioSla"))
        {
                return getRisorsaPdMonitoraggioSla();
            }
          if (name.equals("RisorsaPdMonitoraggioStato"))
        {
                return getRisorsaPdMonitoraggioStato();
            }
          return null;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
          if (name.equals(ConfigurazioneSPPeer.ID))
        {
                return getId();
            }
          if (name.equals(ConfigurazioneSPPeer.URL_FREESBEE_SP))
        {
                return getUrlFreesbeeSp();
            }
          if (name.equals(ConfigurazioneSPPeer.RISORSA))
        {
                return getRisorsa();
            }
          if (name.equals(ConfigurazioneSPPeer.AUTENTICAZIONE))
        {
                return getAutenticazione();
            }
          if (name.equals(ConfigurazioneSPPeer.RISORSA_PD_MONITORAGGIO_SLA))
        {
                return getRisorsaPdMonitoraggioSla();
            }
          if (name.equals(ConfigurazioneSPPeer.RISORSA_PD_MONITORAGGIO_STATO))
        {
                return getRisorsaPdMonitoraggioStato();
            }
          return null;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
            if (pos == 0)
        {
                return getId();
            }
              if (pos == 1)
        {
                return getUrlFreesbeeSp();
            }
              if (pos == 2)
        {
                return getRisorsa();
            }
              if (pos == 3)
        {
                return getAutenticazione();
            }
              if (pos == 4)
        {
                return getRisorsaPdMonitoraggioSla();
            }
              if (pos == 5)
        {
                return getRisorsaPdMonitoraggioStato();
            }
              return null;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
          save(ConfigurazioneSPPeer.getMapBuilder()
                .getDatabaseMap().getName());
      }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
       * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
       *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
          try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
      }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
          if (!alreadyInSave)
        {
            alreadyInSave = true;


  
            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    ConfigurazioneSPPeer.doInsert((ConfigurazioneSP) this, con);
                    setNew(false);
                }
                else
                {
                    ConfigurazioneSPPeer.doUpdate((ConfigurazioneSP) this, con);
                }
                }

                      alreadyInSave = false;
        }
      }

                  
      /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param key id ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        
    {
            setId(new Long(((NumberKey) key).longValue()));
        }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) 
    {
            setId(new Long(key));
        }

  
    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
          return SimpleKey.keyFor(getId());
      }
 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
       * It then fills all the association collections and sets the
     * related objects to isNew=true.
       */
      public ConfigurazioneSP copy() throws TorqueException
    {
        return copyInto(new ConfigurazioneSP());
    }
  
    protected ConfigurazioneSP copyInto(ConfigurazioneSP copyObj) throws TorqueException
    {
          copyObj.setId(id);
          copyObj.setUrlFreesbeeSp(urlFreesbeeSp);
          copyObj.setRisorsa(risorsa);
          copyObj.setAutenticazione(autenticazione);
          copyObj.setRisorsaPdMonitoraggioSla(risorsaPdMonitoraggioSla);
          copyObj.setRisorsaPdMonitoraggioStato(risorsaPdMonitoraggioStato);
  
                    copyObj.setId((Long)null);
                                          
                return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public ConfigurazioneSPPeer getPeer()
    {
        return peer;
    }


    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("ConfigurazioneSP:\n");
        str.append("Id = ")
               .append(getId())
             .append("\n");
        str.append("UrlFreesbeeSp = ")
               .append(getUrlFreesbeeSp())
             .append("\n");
        str.append("Risorsa = ")
               .append(getRisorsa())
             .append("\n");
        str.append("Autenticazione = ")
               .append(getAutenticazione())
             .append("\n");
        str.append("RisorsaPdMonitoraggioSla = ")
               .append(getRisorsaPdMonitoraggioSla())
             .append("\n");
        str.append("RisorsaPdMonitoraggioStato = ")
               .append(getRisorsaPdMonitoraggioStato())
             .append("\n");
        return(str.toString());
    }
}
