package it.unibas.freesbeesla.tracciatura.modello.base;


import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.ObjectUtils;
import org.apache.torque.TorqueException;
import org.apache.torque.om.BaseObject;
import org.apache.torque.om.ComboKey;
import org.apache.torque.om.DateKey;
import org.apache.torque.om.NumberKey;
import org.apache.torque.om.ObjectKey;
import org.apache.torque.om.SimpleKey;
import org.apache.torque.om.StringKey;
import org.apache.torque.om.Persistent;
import org.apache.torque.util.Criteria;
import org.apache.torque.util.Transaction;

import it.unibas.freesbeesla.tracciatura.modello.*;

import it.unibas.freesbeesla.tracciatura.modello.dao.*;

    

/**
 * This class was autogenerated by Torque on:
 *
 * [Tue Dec 14 20:27:47 CET 2010]
 *
 * You should not use this class directly.  It should not even be
 * extended all references should be to SoggettoSLA
 */
public abstract class BaseSoggettoSLA extends BaseObject
{
    /** The Peer class */
    private static final SoggettoSLAPeer peer =
        new SoggettoSLAPeer();

        
    /** The value for the id field */
    private Long id;
      
    /** The value for the nomeSoggetto field */
    private String nomeSoggetto;
  
            
    /**
     * Get the Id
     *
     * @return Long
     */
    public Long getId()
    {
        return id;
    }

                        
    /**
     * Set the value of Id
     *
     * @param v new value
     */
    public void setId(Long v) 
    {
    
                  if (!ObjectUtils.equals(this.id, v))
              {
            this.id = v;
            setModified(true);
        }
    
          
              }
          
    /**
     * Get the NomeSoggetto
     *
     * @return String
     */
    public String getNomeSoggetto()
    {
        return nomeSoggetto;
    }

                        
    /**
     * Set the value of NomeSoggetto
     *
     * @param v new value
     */
    public void setNomeSoggetto(String v) 
    {
    
                  if (!ObjectUtils.equals(this.nomeSoggetto, v))
              {
            this.nomeSoggetto = v;
            setModified(true);
        }
    
          
              }
  
         
                
    private static List fieldNames = null;

    /**
     * Generate a list of field names.
     *
     * @return a list of field names
     */
    public static synchronized List getFieldNames()
    {
        if (fieldNames == null)
        {
            fieldNames = new ArrayList();
              fieldNames.add("Id");
              fieldNames.add("NomeSoggetto");
              fieldNames = Collections.unmodifiableList(fieldNames);
        }
        return fieldNames;
    }

    /**
     * Retrieves a field from the object by name passed in as a String.
     *
     * @param name field name
     * @return value
     */
    public Object getByName(String name)
    {
          if (name.equals("Id"))
        {
                return getId();
            }
          if (name.equals("NomeSoggetto"))
        {
                return getNomeSoggetto();
            }
          return null;
    }

    /**
     * Retrieves a field from the object by name passed in
     * as a String.  The String must be one of the static
     * Strings defined in this Class' Peer.
     *
     * @param name peer name
     * @return value
     */
    public Object getByPeerName(String name)
    {
          if (name.equals(SoggettoSLAPeer.ID))
        {
                return getId();
            }
          if (name.equals(SoggettoSLAPeer.NOME_SOGGETTO))
        {
                return getNomeSoggetto();
            }
          return null;
    }

    /**
     * Retrieves a field from the object by Position as specified
     * in the xml schema.  Zero-based.
     *
     * @param pos position in xml schema
     * @return value
     */
    public Object getByPosition(int pos)
    {
            if (pos == 0)
        {
                return getId();
            }
              if (pos == 1)
        {
                return getNomeSoggetto();
            }
              return null;
    }
     
    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
     *
     * @throws Exception
     */
    public void save() throws Exception
    {
          save(SoggettoSLAPeer.getMapBuilder()
                .getDatabaseMap().getName());
      }

    /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.
       * Note: this code is here because the method body is
     * auto-generated conditionally and therefore needs to be
     * in this file instead of in the super class, BaseObject.
       *
     * @param dbName
     * @throws TorqueException
     */
    public void save(String dbName) throws TorqueException
    {
        Connection con = null;
          try
        {
            con = Transaction.begin(dbName);
            save(con);
            Transaction.commit(con);
        }
        catch(TorqueException e)
        {
            Transaction.safeRollback(con);
            throw e;
        }
      }

      /** flag to prevent endless save loop, if this object is referenced
        by another object which falls in this transaction. */
    private boolean alreadyInSave = false;
      /**
     * Stores the object in the database.  If the object is new,
     * it inserts it; otherwise an update is performed.  This method
     * is meant to be used as part of a transaction, otherwise use
     * the save() method and the connection details will be handled
     * internally
     *
     * @param con
     * @throws TorqueException
     */
    public void save(Connection con) throws TorqueException
    {
          if (!alreadyInSave)
        {
            alreadyInSave = true;


  
            // If this object has been modified, then save it to the database.
            if (isModified())
            {
                if (isNew())
                {
                    SoggettoSLAPeer.doInsert((SoggettoSLA) this, con);
                    setNew(false);
                }
                else
                {
                    SoggettoSLAPeer.doUpdate((SoggettoSLA) this, con);
                }
                }

                      alreadyInSave = false;
        }
      }

                  
      /**
     * Set the PrimaryKey using ObjectKey.
     *
     * @param key id ObjectKey
     */
    public void setPrimaryKey(ObjectKey key)
        
    {
            setId(new Long(((NumberKey) key).longValue()));
        }

    /**
     * Set the PrimaryKey using a String.
     *
     * @param key
     */
    public void setPrimaryKey(String key) 
    {
            setId(new Long(key));
        }

  
    /**
     * returns an id that differentiates this object from others
     * of its class.
     */
    public ObjectKey getPrimaryKey()
    {
          return SimpleKey.keyFor(getId());
      }
 

    /**
     * Makes a copy of this object.
     * It creates a new object filling in the simple attributes.
       * It then fills all the association collections and sets the
     * related objects to isNew=true.
       */
      public SoggettoSLA copy() throws TorqueException
    {
        return copyInto(new SoggettoSLA());
    }
  
    protected SoggettoSLA copyInto(SoggettoSLA copyObj) throws TorqueException
    {
          copyObj.setId(id);
          copyObj.setNomeSoggetto(nomeSoggetto);
  
                    copyObj.setId((Long)null);
                  
                return copyObj;
    }

    /**
     * returns a peer instance associated with this om.  Since Peer classes
     * are not to have any instance attributes, this method returns the
     * same instance for all member of this class. The method could therefore
     * be static, but this would prevent one from overriding the behavior.
     */
    public SoggettoSLAPeer getPeer()
    {
        return peer;
    }


    public String toString()
    {
        StringBuffer str = new StringBuffer();
        str.append("SoggettoSLA:\n");
        str.append("Id = ")
               .append(getId())
             .append("\n");
        str.append("NomeSoggetto = ")
               .append(getNomeSoggetto())
             .append("\n");
        return(str.toString());
    }
}
