package it.unibas.icar.freesbee.ws.client.profiloegov.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-06-22T17:59:26.855+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://icar.unibas.it/freesbee/", name = "IWSProfiloEGov")
@XmlSeeAlso({ObjectFactory.class})
public interface IWSProfiloEGov {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "addProfiloEGov", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.profiloegov.cxf.AddProfiloEGov")
    @WebMethod
    @ResponseWrapper(localName = "addProfiloEGovResponse", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.profiloegov.cxf.AddProfiloEGovResponse")
    public long addProfiloEGov(
        @WebParam(name = "profiloEGov", targetNamespace = "")
        it.unibas.icar.freesbee.ws.client.profiloegov.cxf.ProfiloEGov profiloEGov
    ) throws SOAPFault_Exception;

    @RequestWrapper(localName = "removeProfiloEGov", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.profiloegov.cxf.RemoveProfiloEGov")
    @WebMethod
    @ResponseWrapper(localName = "removeProfiloEGovResponse", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.profiloegov.cxf.RemoveProfiloEGovResponse")
    public void removeProfiloEGov(
        @WebParam(name = "profiloEGov", targetNamespace = "")
        long profiloEGov
    ) throws SOAPFault_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getProfiloEGov", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.profiloegov.cxf.GetProfiloEGov")
    @WebMethod
    @ResponseWrapper(localName = "getProfiloEGovResponse", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.profiloegov.cxf.GetProfiloEGovResponse")
    public it.unibas.icar.freesbee.ws.client.profiloegov.cxf.ProfiloEGov getProfiloEGov(
        @WebParam(name = "profiloEGov", targetNamespace = "")
        long profiloEGov
    ) throws SOAPFault_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getListaProfiliEGov", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.profiloegov.cxf.GetListaProfiliEGov")
    @WebMethod
    @ResponseWrapper(localName = "getListaProfiliEGovResponse", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.profiloegov.cxf.GetListaProfiliEGovResponse")
    public java.util.List<it.unibas.icar.freesbee.ws.client.profiloegov.cxf.ProfiloEGov> getListaProfiliEGov() throws SOAPFault_Exception;
}
