package it.unibas.icar.freesbee.ws.client.accordoservizio.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-06-22T17:23:47.417+02:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://icar.unibas.it/freesbee/", name = "IWSAccordoServizio")
@XmlSeeAlso({ObjectFactory.class})
public interface IWSAccordoServizio {

    @RequestWrapper(localName = "addAccordoServizio", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.accordoservizio.cxf.AddAccordoServizio")
    @WebMethod
    @ResponseWrapper(localName = "addAccordoServizioResponse", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.accordoservizio.cxf.AddAccordoServizioResponse")
    public void addAccordoServizio(
        @WebParam(name = "accordoServizio", targetNamespace = "")
        it.unibas.icar.freesbee.ws.client.accordoservizio.cxf.AccordoServizio accordoServizio
    ) throws SOAPFault_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getListaAccordiServizio", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.accordoservizio.cxf.GetListaAccordiServizio")
    @WebMethod
    @ResponseWrapper(localName = "getListaAccordiServizioResponse", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.accordoservizio.cxf.GetListaAccordiServizioResponse")
    public java.util.List<it.unibas.icar.freesbee.ws.client.accordoservizio.cxf.AccordoServizio> getListaAccordiServizio() throws SOAPFault_Exception;

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAccordoServizio", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.accordoservizio.cxf.GetAccordoServizio")
    @WebMethod
    @ResponseWrapper(localName = "getAccordoServizioResponse", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.accordoservizio.cxf.GetAccordoServizioResponse")
    public it.unibas.icar.freesbee.ws.client.accordoservizio.cxf.AccordoServizio getAccordoServizio(
        @WebParam(name = "accordoServizio", targetNamespace = "")
        long accordoServizio
    ) throws SOAPFault_Exception;

    @RequestWrapper(localName = "removeAccordoServizio", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.accordoservizio.cxf.RemoveAccordoServizio")
    @WebMethod
    @ResponseWrapper(localName = "removeAccordoServizioResponse", targetNamespace = "http://icar.unibas.it/freesbee/", className = "it.unibas.icar.freesbee.ws.client.accordoservizio.cxf.RemoveAccordoServizioResponse")
    public void removeAccordoServizio(
        @WebParam(name = "accordoServizio", targetNamespace = "")
        long accordoServizio
    ) throws SOAPFault_Exception;
}
