package it.unibas.freesbeesla.tracciatura.modello.dao;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Apr 09 20:36:30 CEST 2009]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class SoggettoSLAPeer
    extends it.unibas.freesbeesla.tracciatura.modello.base.BaseSoggettoSLAPeer
{
}
