package it.unibas.icar.freesbee.ws.client.configurazione.cxf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2013-03-08T12:22:17.248+01:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "Configurazione", 
                  wsdlLocation = "http://localhost:8191/ws/configurazione?wsdl",
                  targetNamespace = "http://web.ws.freesbee.icar.unibas.it/") 
public class Configurazione_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://web.ws.freesbee.icar.unibas.it/", "Configurazione");
    public final static QName WSConfigurazioneImplPort = new QName("http://web.ws.freesbee.icar.unibas.it/", "WSConfigurazioneImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8191/ws/configurazione?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Configurazione_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8191/ws/configurazione?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Configurazione_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Configurazione_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Configurazione_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns IWSConfigurazione
     */
    @WebEndpoint(name = "WSConfigurazioneImplPort")
    public IWSConfigurazione getWSConfigurazioneImplPort() {
        return super.getPort(WSConfigurazioneImplPort, IWSConfigurazione.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWSConfigurazione
     */
    @WebEndpoint(name = "WSConfigurazioneImplPort")
    public IWSConfigurazione getWSConfigurazioneImplPort(WebServiceFeature... features) {
        return super.getPort(WSConfigurazioneImplPort, IWSConfigurazione.class, features);
    }

}
